### ISSUE TITLE
Question: Reading the PDF from a URL

### ISSUE THREAD

**Issue by keto33** [kermitt2/grobid#1004]
I run the command:

`curl -sS --form input=@/file.pdf localhost:8070/api/processFulltextDocument > /x.xml
`

I wonder if there is a way to read the PDF file from a URL rather than a local file. Something like:

`curl -sS --form input=https://example.com/x.pdf localhost:8070/api/processFulltextDocument > /x.xml`

**Comment by kermitt2** [comment]
Hi @keto33 !

Thanks for the issue. 

This is not supported and there is no plan to add that for security reasons. It would also have no particular advantage for performance because the PDF processing is not streamed for safety (that would not be safe with corrupted, ill-formed and gigantic PDF).

So I would say the best would be to add a download pipeline calling the service. 

For inspiration/reuse, the following project is doing this more or less, downloading and processing PDF in parallel: [article_dataset_builder](https://github.com/kermitt2/article_dataset_builder)
