### ISSUE TITLE
 Grobid's recognition accuracy for Chinese PDF is too low

### ISSUE THREAD

**Issue by stone-98** [kermitt2/grobid#1034]
- What is your OS and architecture? Windows is not supported and Mac OS arm64 is not yet supported. For non-supported OS, you can use Docker (https://grobid.readthedocs.io/en/latest/Grobid-docker/)

The recognition rate of Chinese PDF using grobid is very low. Can I train the Chinese model by myself to improve the accuracy of grobid for Chinese PDF?

- What is your Java version (`java --version`)? 

- In case of build or run errors, please submit the error while running gradlew with ``--stacktrace`` and ``--info`` for better log traces (e.g. `./gradlew run --stacktrace --info`) or attach the log file `logs/grobid-service.log`.

**Comment by kermitt2** [comment]
> The recognition rate of Chinese PDF using grobid is very low. 

Yes this is to be expected because unfortunately there is almost zero example in Chinese in the training data.
There are only some examples in Chinese for the model that parse references.

> Can I train the Chinese model by myself to improve the accuracy of grobid for Chinese PDF?

Yes absolutely ! 

This question was discussed here -> https://github.com/kermitt2/grobid/issues/279

I also saw this repository at some point, which might be relevant to training data for Chinese: https://github.com/coloyellow/TLGTD
