### ISSUE TITLE
PDF Parsing Question with Japanese or Chinese PDF

### ISSUE THREAD

**Issue by hifiveszu** [kermitt2/grobid#1049]
Hi everyone!
I'm having some issues with using Grobid for PDF extraction. Can someone help me identify the problem? 
It can parse English PDFs completely, but for Chinese and Japanese, it only extracts very little content.

pdf sources:
[gaiyo2023_07.pdf](https://github.com/kermitt2/grobid/files/12556079/gaiyo2023_07.pdf)
[CPG Management of Cervical Cancer (Second Edition).pdf](https://github.com/kermitt2/grobid/files/12556081/CPG.Management.of.Cervical.Cancer.Second.Edition.pdf)

parse config:
![image](https://github.com/kermitt2/grobid/assets/15151837/2a66f233-8b2e-4953-ad36-d6e16ed77907)

Here are tei file I download from server( I rename the files, the right suffix is .tei.xml ):

[gaiyo2023_07.pdf.txt](https://github.com/kermitt2/grobid/files/12556097/gaiyo2023_07.pdf.txt)
[CPG Management of Cervical Cancer (Second Edition).txt](https://github.com/kermitt2/grobid/files/12556092/CPG.Management.of.Cervical.Cancer.Second.Edition.txt)

**Comment by kermitt2** [comment]
Hello @hifiveszu !

The segmentation and body parsing models are trained only with English (with a bit of German and French). Chinese and Japanese fonts and encodings are working, but then Grobid can't identify header, sections, paragraphs, etc. because it has no training data. The result is thus a bit random, mainly recognized as formula and figure content (which is filtered out, because usually SVG content). 

To support Chinese and Japanese, training data for these languages would be necessary.

**Comment by hifiveszu** [comment]
@kermitt2 Thanks
