### ISSUE TITLE
DOI extracted wrongly from the references

### ISSUE THREAD

**Issue by Aazhar** [kermitt2/grobid#105]
I'm getting a false DOI, GROBID is supposed to look for the DOI in the header(firs pages) of the article whereas with this example https://hal.archives-ouvertes.fr/hal-01245634v2/document, a bad DOI is extracted from references (end of the document).

**Comment by kermitt2** [comment]
Issue only full text processing… commit fe58f749f24b90c1f8f060294c02856404d8e5ba should fix the problem, but it requires a bit more test.

**Comment by liar666** [comment]
Hi,

Sure it is better to correct the code, but wouldn't such an error be corrected by using the Crossref service calls?

GM

**Comment by kermitt2** [comment]
Hello! 
Well the call to CrossRef is currently costly, so it is better to prevent using it with an incorrect DOI. The problem here was simply that after an update of the "page" layout structure representation (made a couple of months ago), when GROBID was trying to find a DOI for the current article, it was going beyond the header and the two first pages, so even until the bibliographical section where thare are often plenty of DOI not related to the current article. So really a bug :/
