### ISSUE TITLE
Official gpu grobid 0.7.3 container consume GPU RAM 20+GB

### ISSUE THREAD

**Issue by sawyerzheng** [kermitt2/grobid#1091]
- What is your OS and architecture? Windows is not supported and Mac OS arm64 is not yet supported. For non-supported OS, you can use Docker (https://grobid.readthedocs.io/en/latest/Grobid-docker/)
Use grobid/grobid:0.7.3 offical gpu docker container in Ubuntu:20.04
GPU: 4090 x 2

![image](https://github.com/kermitt2/grobid/assets/44355570/b7c949a2-efa7-40ea-bf0d-78b6b959bcac)

Please look the notice in the picture.

Question:

1. Is it normal for consuming 20+GB GPU RAM in two GPU ?

2. How to set the weight distribution ratio on different GPU?

**Comment by lfoppiano** [comment]
I don't have access to a working machine with GPU at this exact moment but I try to answer your questions: 

1. I think is normal that the first GPU's memory is fully used and the second only partially. This is due to Tensorflow's behaviour. 
2. You can limit the number of GPU using the environment variable `CUDA_VISIBLE_DEVICES="0"` to limit on the first GPU or CUDA_VISIBLE_DEVICES="0,1,2" etc... to enable multiple GPUs. In general, the deep learning models by default run on a single GPU.

**Comment by sawyerzheng** [comment]
We fixed this problem by setting `TF_FORCE_GPU_ALLOW_GROWTH=true`. Thanks after all.

**Comment by lfoppiano** [comment]
@sawyerzheng great. I'm glad you solved. 

What happens when you set that flag to true? Could you show me the same screenshot as above with the TF_FORCE_GPU_ALLOW_GROWTH=true
