### ISSUE TITLE
Affiliation markers annotation

### ISSUE THREAD

**Issue by ArchanaHole** [kermitt2/grobid#110]
Can the system classify various affiliations of a single author in author group by representing it with any identifier?

**Comment by kermitt2** [comment]
Hello! Could you give us an example to clarify your request? Thanks!

**Comment by ArchanaHole** [comment]
In the example given below, the first name and surname of the author  has been identified with attributes 'forename', 'surname', respectively. However, the affiliation given as number 1 along with author name has no attribute when the information is extracted from PDF to TEI format.

Example: 
Adam Smith<sup>1</sup>

<author>
<persName>
<forename type="first">Adam</forename>
<surname>Smith</surname>
</persName>
<email>E-mail: abc.xyzmr@wu.ac.at.</email>
<affiliation>
<orgName type="department">XXX</orgName>
<orgName type="institution">XXX</orgName>
<address>
<addrLine>XXX</addrLine>
<postCode>SSS</postCode>
<settlement>AAA</settlement>
<country key="AT">Austria</country>
</address>
</affiliation>
</author>

Please provide your suggestion for the same.

**Comment by kermitt2** [comment]
Thanks! If I understand correctly you would like that the extracted affiliation marker ```1``` appears in the element ```<affiliation>``` as attribute? Currently it is not outputted in the resulting TEI for different reasons:  
- in the TEI it is useless for relating the author to the affiliation, because the structure explicitely indicates that the affiliation is attached to the author (sibling nodes),
- the affiliation marker has only a presentation purpose, it is not part of the logical structure (for presentation, we could take any markers, or indicate the relation based on grouping display) - the goal of the tool is to capture the logical structure of the document, not the presentation choices,
- it is not always easy to extract precisely the affiliation marker from the PDF (weird character, superscript, etc.), so it would add a (new) potential source of error.

As an additional remark, the affiliation marker used in the PDF could be any kind of weird characters, so it would also not be safe to have it as an attribute value, it would need to be introduced by a dedicated element and the marker would appear as PC-DATA. 

So I am not convinced by the value for the user of outputting the extracted affiliation marker in the resulting TEI document. What we could do is to set an ```@xml:id``` with an identifier (```aff1``` for instance) on the ```<affiliation>``` element, which can useful to explicitely indicate that a given affiliation is common between several authors.

**Comment by ArchanaHole** [comment]
Thanks for your speedy response. 
We are good to go with the solution provided by you i.e., @xml:id with an identifier. However, we would suggest you to add an attribute for corresponding author too. For example, in the attached sample second author signifies the corresponding author who is represented with an asterisk. After extraction, please extract the information of corresponding author similar to @xml:id identifier. 

We would be glad if you could please share us the possible date on which we will be able to test at our end.
[Author.txt](https://github.com/kermitt2/grobid/files/401494/Author.txt)

**Comment by kermitt2** [comment]
I am not sure to understand your reply, the corresponding author - when spotted by the GROBID - is already identified with a @role attribute, e.g.  

```
<author role="corresp">
	<persName>
		<forename type="first">Catherine</forename>
		<surname>xxx</surname>
		<roleName>Md</roleName>
	</persName>
	<email>E-mail: catherine.xxx@yyy.ca</email>
</author>
```

Are you talking about this existing feature?

**Comment by ArchanaHole** [comment]
Yes, I am taking about the same feature.
However, I am not getting "author role" attribute in final TEL output.

**Comment by ArchanaHole** [comment]
We would be glad if you could please tell us whether the reported issue "@xml:id with an identifier" has been taken into consideration or not?
Also, for corresponding author I am not getting the output with author role attribute.

**Comment by kermitt2** [comment]
It has been taken into consideration ;)
There are a couple of tricky cases where the same affiliation (or a partial one) is repeated on the same PDF for several authors, so there is a small sub-issue related to affiliation matching which is not straightforward. Let's try to implement it this month. 

Regarding the other problem related to the corresponding author, this is specific to your example and I would need to be able to reproduce the error to see what can be the reason for not identifying the role of corresponding author - there can be many different reasons for this. If your example is an open access paper (e.g. arXiv), please attach it to the issue, otherwise just give me the URL to the paper - thanks!

**Comment by ArchanaHole** [comment]
Sorry for late response.
Please find attachment for the requested sample. 
Can you please update me, when can I test requirement "xml: affiliation id identifier" in TEI file.

Thanks
[Grobid.pdf](https://github.com/kermitt2/grobid/files/419840/Grobid.pdf)

**Comment by kermitt2** [comment]
Thanks! In this example, I don't see how we could really consider the first author as the corresponding author. The ```*``` marker makes the association with the email marked with a ```*```, but the fact that this is the corresponding author is a bit speculative even for a human. Usually for indicating that one author is the corresponding author, something explicit would be required somewhere like a mention "corresponding author", "author to whom correspondence should be addressed", etc. that could help to distinguish one of the authors from the others.

Not the problem raised, but there is an error in the affiliations of the second author, they are not identified as two separate affiliations. This can be fixed I think by completing a bit the training data.

**Comment by ArchanaHole** [comment]
Thanks for your reply.
I have attached one PDF wherein I have noticed below issues. 
1.  I have added 'corresponding author'  text just to distinguish corresponding author from rest of the co authors. Still Corresponding role is missing in TEL file. Rather author name got repeated twice.
2.  Mail ID for all author got removed.
3. Tel number got removed 
Please check and keep posting me your analysis.
Also, please keep me posted in regards to 'xml affiliation ID' generation issue. It will be good if you can tell me tentative date when it can be available to me for testing.
In regards to second point from your reply, I thought to create separate ticket for wrong identification.
Please let me know your thought on this. 
[Final Use of Short Roll 1.pdf](https://github.com/kermitt2/grobid/files/429592/Final.Use.of.Short.Roll.1.pdf)

**Comment by ArchanaHole** [comment]
I would request your goodself to please share me your availability to discuss the issues via go to meeting. It would be helpful to get an overview of the project. I would be glad to know the progress of the development for the reported feedback. If you have any other alternative means of communication, please do let me know.

**Comment by kermitt2** [comment]
The addition of an attribute to identify the same affiliation distributed to different authors has been introduced in commit 2f38805c919ac39d17f0bd2223952d04498f6a0d. 

The added attribute is @key to element ```<affiliation>```, which is valid in TEI (@xml:id was not possible because it is for identifying an XML node in a unique manner).

Regarding the problem of identifying the corresponding author, I open another issue.

**Comment by ArchanaHole** [comment]
Thanks a lot for fixing this issue. 

For the attached PDF, wrong affiliation ID got assigned to the author 'Atef Atyaoui'

**Comment by kermitt2** [comment]
`@corresp` author should be well identified in general now, for example in your PDF:

```xml
                        <author role="corresp">
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">Badreddine</forename>
                                <surname>Barhoumi</surname>
                            </persName>
                            <email>barhoumibadredine@yahoo.fr</email>
                            <affiliation key="aff0">
                                <orgName type="department" key="dep1">Department of Chemistry</orgName>
                                <orgName type="department" key="dep2">Faculty of Sciences of Bizerte</orgName>
                                <orgName type="laboratory">Laboratory of Heteroatom Organic Chemistry</orgName>
                                <orgName type="institution">University of Carthage</orgName>
                                <address>
                                    <addrLine>Four Fountains Road</addrLine>
                                    <postCode>7021</postCode>
                                    <settlement>Jarzouna</settlement>
                                    <country key="TN">Tunisia</country>
                                </address>
                            </affiliation>
                            <affiliation key="aff1">
                                <orgName type="laboratory">UMR CNRS EPOC 5805</orgName>
                                <orgName type="institution">University of Bordeaux</orgName>
                                <address>
                                    <addrLine>10 N Two Pier Avenue</addrLine>
                                    <postCode>33405</postCode>
                                    <settlement>Talence Cedex</settlement>
                                    <country key="FR">France</country>
                                </address>
                            </affiliation>
                        </author>
```

In addition, Atef Atyaoui has the correct affiliations:

```xml
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">Atef</forename>
                                <surname>Atyaoui</surname>
                            </persName>
                            <affiliation key="aff2">
                                <orgName type="department" key="dep1">Department of Earth Sciences</orgName>
                                <orgName type="department" key="dep2">Faculty of Sciences of Bizerte</orgName>
                                <orgName type="institution">University of Carthage</orgName>
                                <address>
                                    <addrLine>Four Fountains Road</addrLine>
                                    <postCode>7021</postCode>
                                    <settlement>Jarzouna</settlement>
                                    <country key="TN">Tunisia</country>
                                </address>
                            </affiliation>
                            <affiliation key="aff4">
                                <orgName type="institution">Delhi University</orgName>
                                <address>
                                    <addrLine>Nine Horses Street, New Delhi</addrLine>
                                    <country key="IN">India</country>
                                </address>
                            </affiliation>
                        </author>
```
