### ISSUE TITLE
Problem with Crossref

### ISSUE THREAD

**Issue by ChangjingZhang** [kermitt2/grobid#1132]
Metadata from Crossref is incomplete. Hope Grobid could combine results from Crossref and its own.

**Comment by kermitt2** [comment]
Hello @ChangjingZhang, this is normally happening. CrossRef metadata are added only when Grobid could not extract the corresponding metadata from the PDF. The only exception is ORCID, which is coming from CrossRef if found, and overwrite possible ORCID extracted from the PDF, because CrossRef appears more reliable for this.
