### ISSUE TITLE
Apptainer Support? `stat ~/grobid-service/bin/grobid-service: no such file or directory`

### ISSUE THREAD

**Issue by KastanDay** [kermitt2/grobid#1150]
I'm attempting to run Grobid in a HPC (high performance compute) environment, they only support [Apptainer](https://apptainer.org/). 

```bash
$ apptainer pull docker://grobid/grobid:0.8.0
# ✅ -- creates grobid_0.8.0.sif

$ apptainer run --nv --no-home --cleanenv grobid_0.8.0.sif -p 8070:8070
stat ~/grobid-service/bin/grobid-service: no such file or directory
# ❌ can't find the grobid-service file. 
```

It feels like there might be an easy work-around. Can I set the PATH properly to link the `grobid-service`?

Any help is greatly appreciated.

**Comment by lfoppiano** [comment]
I think, the script is on the following path: `/opt/grobid/grobid-service/bin/grobid-service`

**Comment by KastanDay** [comment]
Apologies, yes, I finally figured this out. Cloning the repo worked great to supply default configs. 
This is resolved, hopefully that helps other apptainer users; just clone the repo.

**Comment by cboulanger** [comment]
@KastanDay Could you elaborate how exactly you solved the issue? I tried cloning the repo but the path `grobid-service/bin/grobid-service` does not exist in the repo. Do I have to create it?

**Comment by cboulanger** [comment]
Ok, after some experimentation I was able to configure the image using a apptainer sandbox instead:

```bash
apptainer build --sandbox grobid_0.8.0/ docker://grobid/grobid:0.8.0
apptainer shell --writable --no-home --cleanenv grobid_0.8.0/
```
In the shell, do the following:
```bash
ln -s /opt/grobid/grobid-* .
sed -i 's|install: "../delft"|install: "/opt/grobid"|g' /opt/grobid/grobid-home/config/grobid.yaml
```

Then exit the shell start the image with 
```bash
apptainer run --nv --no-home --cleanenv grobid_0.8.0/
```
to see if everything works. I am getting a couple of errors such as 

```
There was a problem when trying to write in your cache folder (.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
BidLSTM_CRF_FEATURES
E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host: /proc/driver/nvidia/version does not exist
``` 
but they seem to be fixable and no fatal errors are reported.

Afterwards, convert the sandbox to a `.sif`-file:

```bash
apptainer build grobid_0.8.0.sif grobid_0.8.0/
```

which you can then start with 

```bash
apptainer run --nv --no-home --cleanenv grobid_0.8.0.sif
```
I haven't yet tested whether everything works as expected, but will update this post when I encounter errors which can be fixed by adapting the sandbox.

**Comment by cboulanger** [comment]
Unfortunately, this breaks when upgrading to apptainer v1.3.2, which might have to do with [changes in path handling in v1.2](https://github.com/apptainer/apptainer/releases/tag/v1.2.0):

```
~> module load apptainer/1.3.2
~> apptainer build --sandbox ~/ptmp_link/grobid_0.8.1/ docker://lfoppiano/grobid:0.8.1-full
~> apptainer shell --writable --no-home --cleanenv  ~/ptmp_link/grobid_0.8.1/
Apptainer> ln -s /opt/grobid/grobid-* .
Apptainer> sed -i 's|./grobid-service/|/opt/grobid/grobid-service/|g' .singularity.d/runscript
Apptainer> sed -i 's|install: "../delft"|install: "/opt/grobid"|g' /opt/grobid/grobid-home/config/grobid.yaml
Apptainer> exit
~> apptainer run --nv --no-home --cleanenv --writable-tmpfs ~/ptmp_link/grobid_0.8.1/
Exception in thread "main" java.lang.RuntimeException: No explicit config provided and cannot find in one of the default locations: [grobid-home/config/grobid.yaml]
        at org.grobid.service.main.GrobidServiceApplication.main(GrobidServiceApplication.java:115)
```

@KastanDay If you could let us know how your exact setup was with which you made it work, that would be wonderful
@lfoppiano Do you have an idea where this error might come from and what would have to be changed so that the GrobidServiceApplication can find the config file?

Thank you

**Comment by cboulanger** [comment]
Oh, figured it out! It's `run --nv --no-mount home,cwd --cleanenv --writable-tmpfs ~/ptmp_link/grobid_0.8.1/` since apptainer v.1.2.

However, the best way of course would be if the path handling could be such that apptainer could use the unmodified docker image. I wonder how this could be done without having to maintain a separate apptainer build definition file.
