### ISSUE TITLE
GROBID Inconsistent Reference Detection in Custom PDFs: Format Guidelines Needed

### ISSUE THREAD

**Issue by JosVuHuynh** [kermitt2/grobid#1154]
What is the correct format for a PDF file that GROBID can detect references in? I create PDFs myself, and sometimes they work and sometimes they don’t. I’m not sure about the formatting rules. Can you please let me know?

**Comment by lfoppiano** [comment]
With "detect references" do you mean, detect reference callout (e.g. `In previous work [1] we showed that...`)? or references sections in the article? 

For the first case, there is generally not much training data in grobid (Fulltext model), but maybe it's easier if you show me some examples of your generated documents.

**Comment by HuynhVuInnomize** [comment]
[noborikawa-paper-one_removed (2).docx.pdf](https://github.com/user-attachments/files/16593307/noborikawa-paper-one_removed.2.docx.pdf)
[GwptVMUJQT.pdf](https://github.com/user-attachments/files/16593308/GwptVMUJQT.pdf)
[T5D17Q7WMj.pdf](https://github.com/user-attachments/files/16593309/T5D17Q7WMj.pdf)
[besG09DFZb.pdf](https://github.com/user-attachments/files/16593310/besG09DFZb.pdf)
[CsoUOcdybT.pdf](https://github.com/user-attachments/files/16593311/CsoUOcdybT.pdf)
Could you review all this file @lfoppiano ?

**Comment by JosVuHuynh** [comment]
[noborikawa-paper-one_removed.pdf](https://github.com/user-attachments/files/16593323/noborikawa-paper-one_removed.pdf)
[GwptVMUJQT.pdf](https://github.com/user-attachments/files/16593324/GwptVMUJQT.pdf)
[T5D17Q7WMj.pdf](https://github.com/user-attachments/files/16593325/T5D17Q7WMj.pdf)
[besG09DFZb.pdf](https://github.com/user-attachments/files/16593326/besG09DFZb.pdf)
[CsoUOcdybT.pdf](https://github.com/user-attachments/files/16593328/CsoUOcdybT.pdf)
Could you review all files @lfoppiano ? Grobid not detect ref when I run on https://huggingface.co/spaces/kermitt2/grobid .

**Comment by lfoppiano** [comment]
There are no "rules" to format a document so that Grobid recognise the references. It's more like, to make a document like a scientific article. 
At a first glance, these document' format is a bit far from the layout of a scientific article. For example, there is no header (at least title and authors) and the page layout is also horizontal (landscape). 

Then, most important, the references don't match the text, so is normal that Grobid does not extract them correctly. 

I did adjust your document and now with some more consistency looks much better ;-) Although, the body look indeed like an abstract: 
[Untitled.pdf](https://github.com/user-attachments/files/16594047/Untitled.pdf)
[Untitled.pdf.tei.xml.zip](https://github.com/user-attachments/files/16594054/Untitled.pdf.tei.xml.zip)
