### ISSUE TITLE
Insertion of line numbers in different TEI tags

### ISSUE THREAD

**Issue by ArchanaHole** [kermitt2/grobid#121]
Issue: 
Line numbers got inserted in following TEI tags while doing extraction of attached PDF.

Line no 11 in country tag  
Line no 12 in addrLine tag
Line no 13 in country tag  
Line no 10 in settlement    tag
Line no 11 in of country tag 
Line no 14 in address line tag  
Line no 15 in address line tag  
Line no 7 in department tag 

[10708_2015_9672_Article.pdf](https://github.com/kermitt2/grobid/files/469609/10708_2015_9672_Article.pdf)

**Comment by kermitt2** [comment]
This one is tricky because the line numbers are inserted like that in the PDF content order. There are similar cases with some PMC author manuscript PDF. This cannot be covered by adding training data because the inserted elements can be anywhere. 

I think it is possible to identified these lines numbers (or similar manuscript/review added elements) either: 
1) at the level of pdf2xml by considering this as an extra column (in the sense of the reading order) or
2) at the level of GROBID processing of the XML file produced by pdf2xml.  

I will experiment approach 1) because it is easier and more efficient I think directly with pdf2xml.

**Comment by kermitt2** [comment]
Grobid now supports line numbers, they are entirely neutralized as visible in this example. 

[10708_2015_9672_Article.tei.xml.tar.gz](https://github.com/kermitt2/grobid/files/5070807/10708_2015_9672_Article.tei.xml.tar.gz)
