### ISSUE TITLE
What can cause: "Could not set GROBID_HOME" ?

### ISSUE THREAD

**Issue by thomasopsomer** [kermitt2/grobid#190]
Hi,
Sorry not really an issue with grobid, but I'm trying to understand what could cause the following error:
`org.grobid.core.exceptions.GrobidPropertyException: [GENERAL] Could not set GROBID_HOME`

Some guesses:
- trying to init a new context without detroying the previous one ?
- trying to init several context in the same JVM ?

I'm asking because I can't reproduce the error on the fly, It just happens sometimes !

My sample code to initiate a grobid context:
```scala
val pGrobidHome: String = sys.env("GROBID_HOME")
val pGrobidProperties: String = pGrobidHome + "/config/grobid.properties"
try {
      MockContext.setInitialContext(pGrobidHome, pGrobidProperties)
      GrobidProperties.getInstance()
}
catch {
      case e: javax.naming.NameAlreadyBoundException => println("grobid already configured")
      case otherE: Exception => otherE.printStackTrace()
}
```

Thanks,
Thomas

PS: Just tried the 0.4.2 snapshot with the new pdf2xml, it really reduce the number of parsing errors  !!

**Comment by thomasopsomer** [comment]
Finally I'm pretty sure it was due to "trying to init several context in the same JVM".

In scala the solution is to wrap grobid into an object, and setting the engine as a "lazy val", useful for a spark job...

**Comment by kermitt2** [comment]
I think this is a context that is set while already existing. This should normally be prevented with the method mockContextIfNotSet() in grobid/grobid-core/src/main/java/org/grobid/core/main/LibraryLoader.java, but it could still exist cases when it's not checked correctly. If you still can reproduce this error, can you give us the full trace of the exception so that we can identify where the context is set without preliminary check? Thanks !

**Comment by thomasopsomer** [comment]
Actually I haven't this issue anymore thanks to lazy instantiation of the the context. But I'll reopen if I reproduce it by chance :)
