### ISSUE TITLE
TEI has Missing Sections

### ISSUE THREAD

**Issue by Zara-Nasar** [kermitt2/grobid#191]
I am using **Grobid 0.4.1** on **Windows** platform and currently performing **fullTextProcessing**. Some section of sub-set of PDFS are missing in TEI.

I have processed these documents into live Grobid web-server, they get parsed successfully. 
(Server is using Grobid 0.4.2 and currently and I am currently having build issues in grobid-home) 

Currently, the attached result altogether skips main heading of the respective PDF document such as  Introduction, Background etc. 

Following is the link to the pdf document and respective TEI is attached..

https://www.researchgate.net/profile/Mahmoud_Shirazi4/publication/287911710_Gauss-Jordan_Matrix_Inversion_Speed-Up_using_GPUs_with_the_Consideration_of_Power_Consumption/links/567a626808aeaa48fa4c37e5.pdf
[60078.fulltext.tei.txt](https://github.com/kermitt2/grobid/files/1043563/60078.fulltext.tei.txt)

Any idea, what could possibly be wrong and how to solve this issue.

**Comment by kermitt2** [comment]
Dear @Zara-Nasar 

First many thanks for reporting the issue.

This problem is related to the cover page added by ResearchGate. The GROBID models are currently trained mostly without any cover pages and their detection is not reliable - it should improve in the future by adding more examples like that in the training data of the segmentation model.

Until that, fixing this issue is very straightforward: simply remove the cover page, and you will see that the structuring is good, without any missing section.    

With your example, have a look at the resulting TEI after removal of the cover page of the PDF (tested with current master): 

https://grobid.s3.amazonaws.com/test.xml

**Comment by Zara-Nasar** [comment]
Thanks :)
I've already tried this via demo Grobid Server (0.4.2-Snapshot) and it gets parsed successfully ( I tried to mention this in question but notion was not that clear, my bad)
The latest stable version i.e. 0.4.1 results into the missing section xml. Any idea what possibly could be the issue, as it works fine for many other pdfs having the same format.

**Comment by kermitt2** [comment]
Ok it's probably simply that the models and features have been updated in version 0.4.2-snapshot, so it is normal and expected to have some improvement. The current master version 0.4.2-snapshot - normally as it is now - is going to be the next stable release. The only blocking thing for this new release version is that the new version pdf2xml would need to be recompiled for Windows 64bit which I can't do unfortunately because I don't have a machine with Windows.

**Comment by Zara-Nasar** [comment]
Can you guide me bit about how to recompile the respective dll for Windows i.e. which code is to be used to get it done. I would like to give it a try.

**Comment by kermitt2** [comment]
So for information, the missing updated library for Windows is the fork of pdf2xml: https://github.com/kermitt2/pdf2xml
Recompiling the dll with this new version would be very welcomed :)
Current old version is under `grobid/grobid-home/pdf2xml/win-64/`

**Comment by Zara-Nasar** [comment]
For information, I am working on it. Currently latest mingw-64 release is not being installed due to an issue in installer file. If I get it working, I will let you know :)

**Comment by Zara-Nasar** [comment]
I've got grobid master development version running in windows-7 64 bit. 
I am unable to upload these binaries as a zip file, thus renamed it with .pdf.

[win-64.zip.pdf](https://github.com/kermitt2/grobid/files/1076572/win-64.zip.pdf)
