### ISSUE TITLE
Figure detection only uses single digit numbers

### ISSUE THREAD

**Issue by rawsh** [kermitt2/grobid#229]
Ref 11. links to fig_0 and ref 1 also links to fig_0.
Also, a lot of figures are missing <figures> and it would be nice if figure 14 was fig_14

**Comment by kermitt2** [comment]
Thanks for the issue regarding identifiers! Do you have test case for these problems? 

Just as a note, identifiers are not related to actual labels, it's just unique XML identifiers. If you want the actual figure label that has been found, you can get it by its label component (XML element `<label>`).

**Comment by rawsh** [comment]
I'm sorry, I meant that the label number was incorrect.
I can't share the pdf I'm using as it's licensed, but here is one where the label fails (xml:id="fig_3"):
https://www.researchgate.net/profile/Carlos_Sanz_De_Galdeano/publication/223706028_Geologic_evolution_of_the_Betic_Cordilleras_in_the_Western_Mediterranean_Miocene_to_the_present/links/54b788020cf2bd04be339df8/Geologic-evolution-of-the-Betic-Cordilleras-in-the-Western-Mediterranean-Miocene-to-the-present.pdf

**Comment by kermitt2** [comment]
So the label of figure with identifier `fig_3` is not recognized because this is not a figure, it's a false positive (too few training data for the moment, and more features needed). 

But I still don't understand the problem with the XML identifier. 

This identifier cannot be related to the figure label actually used, because this label is not always correctly extracted - as for this example - so it would be impossible to choose the actual figure label as XML identifier. XML identifiers are just arbitrary strings.

**Comment by rawsh** [comment]
Oh, ok; I thought the xml id would represent the same number as the figure. I think there should be field, e.g. name, that has the figure number, so that FIgure 12 would have name=12

**Comment by kermitt2** [comment]
As I wrote above, this field exists it's the XML element <label>.

**Comment by rawsh** [comment]
ok
