### ISSUE TITLE
Parsing many raw references in one command

### ISSUE THREAD

**Issue by dtkaczyk** [kermitt2/grobid#243]
I would like to parse quickly a lot of references. My data contains TXT files with raw references only (one per line). I tried using "processRawReference" batch command, but it takes a few seconds on my laptop to process one reference this way, which sums up to many days (even weeks) of processing. It seems that most of this time is spent not on tagging, but on loading the models, etc. Is it possible to pass more raw reference strings to GROBID and process them all after loading the necessary resources once? I did not find such command in the documentation.

**Comment by kermitt2** [comment]
Hello @dtkaczyk 

Simply use the web service, models are not reloaded and you can send requests in parallel (by default up to 10 requests are processed in parallel). 
Even with one thread, you should process at least 100 bibliographical references per second and with parallel requests one can reach 2 millions per hour (without the consolidation option, which is limited by CrossRef API with 25-50 requests per seconds). 

Actually, I plan to remove entirely the batch commands because people end up using only it and the performance are obviously abyssal as compared to the web services, where models are always warm.

**Comment by dtkaczyk** [comment]
@kermitt2 thank you, indeed it seems it's fast enough with the web service. I have never used it before and had no idea it's going to be faster.

**Comment by kermitt2** [comment]
It's indicated in the documentation actually (in particular in the first paragraph of the batch mode documentation pages).

The bib. ref. model has improved considerably during the last weeks (new features, new training data, some new fields), be sure to use the current master version of GROBID ;)
