### ISSUE TITLE
Using grobid core inside a jar

### ISSUE THREAD

**Issue by rawsh** [kermitt2/grobid#245]
I'm trying to make a aws elastic beanstalk service. You need to upload a jar to get it to work, and by using jetty as a server and maven to make a dependency jar it works. But how can I point to the grobid home files inside the jar? Locally it works but calling the jar gives an error saying the grobid home folder was not found.

**Comment by kermitt2** [comment]
Hello @rawsh 

It is not possible to have the grobid home in a jar and use getResourceAsStream() because of the JNI libs - the C methods (which makes GROBID fast) require file system resources. 

For using GROBID as a java library, you need to load the grobid-home as documented. 

When creating the GROBID service, you will see both a war and a separate zip which contains the GROBID home - both need to be deployed, this is the proposed service deployment method that comes with GROBID and we didn't find a better solution given the JNI constraints.

**Comment by rawsh** [comment]
@kermitt2 OK, thanks for the info.
