### ISSUE TITLE
Latest version doesn't used well in maven

### ISSUE THREAD

**Issue by yaojl2006** [kermitt2/grobid#259]
In the latest grobid, I have to inject every dependency manually when using grobid jar file in maven may beacuse there`s no pom.xml in jar.

Is there any method could let maven project automatically injects all dependencies of grobid which packed by gradle?

Thank you.

**Comment by kermitt2** [comment]
Hello!

I am a gradle newbie, but I am still awake and, if I am not wrong, the corresponding pom is generated under `grobid/grobid-core/build/poms/pom-default.xml`
You could also exploit the pom file of the grobid-example project: https://github.com/kermitt2/grobid-example
The dependencies for running the jar are there, so normally you could just cut and paste (grobid-example is up-to-date normally!).

Hope it answers your issue - otherwise our gradle god will definitively help :D

**Comment by yaojl2006** [comment]
It`s embarrassed that I'm a gradle noob, Actually I know almost nothing about this stuff.....

I'll try it, thank you for your gentleness and patience : )

**Comment by kermitt2** [comment]
Hello @yaojl2006, did you manage to have it working with the generated default `pom.xml` file?

**Comment by yaojl2006** [comment]
Hi @kermitt2 ,
Sorry for the late reply. 
I've run grobid well using the default pom file, thank you for your answer!
