### ISSUE TITLE
Docs suggest setting Grobid home by environment variable, but not supported

### ISSUE THREAD

**Issue by borkdude** [kermitt2/grobid#286]
The code example at https://grobid.readthedocs.io/en/latest/Grobid-java-library/ suggests setting the Grobid home directory with an environment variable:

    location (classpath, ../grobid-home, ../../grobid-home or in the environment variable GROBID_HOME

but when I try this, it doesn't work. Glancing at the source code, this variable is not read at all.

https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/main/GrobidHomeFinder.java

**Comment by kermitt2** [comment]
Hello @borkdude !
We can't anymore set the Grobid home directory with an environment variable, we remove this possibility because it was not considered a good practice (for instance when working with different grobid-home). 
Unfortunately I forget to update this comment in this part of the doc...
With the Java library, the way to go for setting GROBID_HOME is the property file.

**Comment by borkdude** [comment]
No problem. Just reporting, not complaining :-) I went with Docker for now anyway.

**Comment by de-code** [comment]
Could we maybe add this back in as an option?
It could use the system property if set, otherwise check the environment variable.
