### ISSUE TITLE
Integrate hyperlinks in citations

### ISSUE THREAD

**Issue by renaud** [kermitt2/grobid#295]
We have several references that contain a link to the doi. For example http://iopscience.iop.org/article/10.1088/0953-8984/27/45/455102/pdf

This is valuable information that ought to be extracted.

**Comment by kermitt2** [comment]
Hello! 
Unfortunately I can't access this publication to test it. 
In the current (master) version, the support for DOI and url should not be too bad (there was an effort on this last summer). They are explicitly extracted, with dedicated labels, and should be present in the result when they are recognized as such. It would be interesting to see why it fails with this paper - is it just with IOP?

**Comment by renaud** [comment]
Oh sorry. The pdf is available at https://www.researchgate.net/profile/Alberto_Fraile3/publication/282876717_Experimental_evidence_for_a_dynamical_crossover_in_liquid_aluminium/links/5623664c08ae70315b5b8e2b/Experimental-evidence-for-a-dynamical-crossover-in-liquid-aluminium.pdf

**Comment by kermitt2** [comment]
@renaud thanks ! I see the problem now, we have the url as annotation on the volume/page. 

This case is definitively not working and this would be very valuable indeed. In the analysis process, all the URL annotations are recognized and an object PDFAnnotation is created, but it is not always outputted. We need to inspect this link to identify such common identifier and instantiate explicitly the identifier field so that it correctly appears in the TEI.

**Comment by kermitt2** [comment]
Added with commit f93e4ab4c074246214cf2d22ddfd1f283e1003de

@renaud you can test it on the demo server -> http://grobid.science-miner.com 
(clicking on consolidate citations give really some nice additions)

**Comment by renaud** [comment]
thanks @kermitt2 , excellent!
