### ISSUE TITLE
Training Citation - Slow

### ISSUE THREAD

**Issue by dhanayanshankar** [kermitt2/grobid#303]
Hey Team, 

The tool is pretty smart and handy to use. The services of the GROBID tool is pretty fast and accurate . Please do check the issue i got with the citation module.

I have run the training module of citation with the command( **gradlew train_citation**) , but found the same executing with 3000 iterations approximately and it took 2 days to complete the same. 

Later on 16GB RAM it was faster with each iteration taking 25-30 seconds and training took almost a day to complete.

Can you please let us know if we can run multiple threads for execution or any such solution to speed up training.

Thanks

**Comment by kermitt2** [comment]
Hello @dhanayanshankar  !

Yes using multiple threads for such a large model is important: edit the file under `grobid-home/config/grobid.properties` and change the following property to the appropriate number of threads

```
grobid.nb_threads=1
```

With 16GB and 10 threads, the training time is much more reasonable (something like 4-5 hours if I remember well, maybe less). Use as many threads as available ;) 

If you still need to speed-up, it is possible to review the training stopping criteria which are not optimized for minimal training time (the idea is more to have them loose so that we can add training data without changing them). For this, edit the file `grobid-trainer/src/main/java/org/grobid/trainer/CitationTrainer.java` and update the parameters `epsilon` (threshold diff. in the objective function loss in a given window of iterations), `window` and `nbMaxIterations`.

**Comment by dhanayanshankar** [comment]
Many thanks for your suggestion ! We have tried with the 10 threads and its pretty fast in execution. It took approximately 12 hours to complete with 3000 iteration. 

Amazed to see the results ! Thanks again
