### ISSUE TITLE
connection to localhost

### ISSUE THREAD

**Issue by LeafyPeafy** [kermitt2/grobid#348]
Hello,
I am using Ubuntu to run a machine learning tool which depends on Grobid. I am getting this output, which just hangs there and then tries again... can't seem to find a fix for it. 
 robotreviewer.textprocessing.pdfreader 2018-09-24 11:43:33,943: Checking if Grobid live...
[DEBUG] urllib3.connectionpool 2018-09-24 11:43:33,990: Starting new HTTP connection (1): localhost:8080

**Comment by kermitt2** [comment]
Hello @LeafyPeafy !

Well it's an issue for robotreviewer... I think it's simply that the default grobid port is now __8070__, and not anymore 8080.

It seems that you need to change the GROBID port under `robotreviewer/config.json`:

```json
"grobid_host": "http://localhost:8070"
```

The rest should be OK I think, but no guarantee because robotreviewer uses GROBID 0.4.1 and we're now at 0.5.1. Alternatively, you could use this older release.

**Comment by LeafyPeafy** [comment]
Excellent... worked great. Thanks so much for your help :-)
