### ISSUE TITLE
Text 'Introduction' is skipped from clinical trial pdfs

### ISSUE THREAD

**Issue by wmotte** [kermitt2/grobid#373]
Substantial clinical trial publications do not explicitly introduce - after the Abstract - the Introduction with a title.
This results in grobid 5.3 (and older versions) in an xml output file with the entire text from the Introduction missing.
This happens, for instance, with this pdf:
PubMed abstract: https://www.ncbi.nlm.nih.gov/pubmed/11118390
Full text: http://www.invivonmr.uu.nl/~wim7/11118390.pdf

Thanks for fixing!

Best wishes, 

Wim Otte

**Comment by kermitt2** [comment]
Hello @wmotte !

Thanks a lot for the error case, very useful. It's a critical issue, and I will work on it with high priority.

**Comment by lfoppiano** [comment]
With grobid 0.5.6 the abstract is correctly recognized but the first column is missing. I'm wondering if we had an improvement over the previous version.  

I wondering whether this issue seems more related to the two columns mentioned in #419 ?

**Comment by kermitt2** [comment]
I didn't describe the problem sorry. The problem is a reading order issue, the left column of the introduction is in the header segment, between the abstract and the rest of the header part ("Received 20 December 1999..." and so on). So because it is not in the body segment, it is not visible in the rest of the document. As it is not recognized as abstract and considered as "noise" by the header model (which is rather correct), it is not visible in the header part. 

This can unfortunately be addressed correctly only with an updated header model and the new reading order from pdfalto. It's quite a lot of work (re-ordering all the training data from the header model) and I've not been able to find the time to really work on this, as I would like, since 2 years :/
Most of the problems related to these sort of problems and missing header metadata extraction come from invalid reading order from the PDF.

**Comment by kermitt2** [comment]
Problem of #419 is not related, #419 is a failure from pdfalto to recognize the 2 columns, it outputs the text as one column.

**Comment by lfoppiano** [comment]
OK, I was not sure, sorry

**Comment by kermitt2** [comment]
After the latest update of the header process+model, this example is working fine.
