### ISSUE TITLE
pdf.js misconfigured on docker image ?

### ISSUE THREAD

**Issue by hdimitriou** [kermitt2/grobid#405]
Using the web service and going to PDF I see on the browser console
`GET https://grobid.atypon.com/resources/pdf.js/build/pdf.js net::ERR_ABORTED 404`

This is reasonable since the whole resources folder is missing
`root@grobid-84cbcddb44-4ns4b:/opt/grobid# ls /opt/grobid/grobid-home/
config	language-detection  lexicon  lib  models  pdf2xml  schemas  tmp`
and 
```
root@grobid-84cbcddb44-4ns4b:/opt/grobid# cat grobid-home/config/grobid.properties
...
##-------------------- start: directories ---------------------
# properties of where to find directories necessary for Grobid
# EACH KEY REFERENCING A PATH HAS TO ENDS WITH ".path"
grobid.resource.path=./resources
```

Out of curiosity, I added pdf.js from mozilla and created the folder structure, that error disappeared but a new popped

```
grobid.js:342 Uncaught ReferenceError: PDFJS is not defined
    at FileReader.reader.onloadend (grobid.js:342)
```

Moreover, when I do such request, the pod (container) restarts promptly with something like this on the logs 
```
...
INFO  [2019-02-26 15:37:11,169] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@40a1b6d4{/,null,AVAILABLE}
INFO  [2019-02-26 15:37:11,257] io.dropwizard.setup.AdminEnvironment: tasks =

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

INFO  [2019-02-26 15:37:11,263] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@79ab97fd{/,null,AVAILABLE}
INFO  [2019-02-26 15:37:11,307] org.eclipse.jetty.server.AbstractConnector: Started application@429aeac1{HTTP/1.1,[http/1.1]}{0.0.0.0:8070}
INFO  [2019-02-26 15:37:11,355] org.eclipse.jetty.server.AbstractConnector: Started admin@79eeff87{HTTP/1.1,[http/1.1]}{0.0.0.0:8071}
INFO  [2019-02-26 15:37:11,355] org.eclipse.jetty.server.Server: Started @16037ms
10.0.10.10 - - [26/Feb/2019:15:37:31 +0000] "GET /resources/pdf.js/build/pdf.js HTTP/1.1" 404 261 "https://grobid.atypon.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36" 74
```

I see that this whole process works on the demo site http://cloud.science-miner.com/grobid/

Can you please explain what I am missing? I am tasked to deploy grobid so I don't know much of its functionality

**Comment by lfoppiano** [comment]
@hdimitriou sorry I missed your issue. I try to have a look this week. 

Which version are you using from docker?

**Comment by hdimitriou** [comment]
"Docker version 18.09.2", "18.06.1-ce"
I am not sure it has to do with the version.

I created my own Dockerfile based on yours and it works fine I think. 
The difference is that i clone your repo inside the builder instead of copying folders.

**Comment by lfoppiano** [comment]
Nothing, sorry I was taking about the grobid version Sent from my Mobile-------- Original Message --------Subject: Re: [kermitt2/grobid] pdf.js misconfigured on docker image ? (#405)From: Harris Dimitriou To: kermitt2/grobid CC: Luca Foppiano ,Assign "Docker version 18.09.2", "18.06.1-ce"
I am not sure it has to do with the version.
I created my own Dockerfile based on yours and it works fine I think.
The difference is that i clone your repo inside the builder instead of copying folders.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kermitt2/grobid","title":"kermitt2/grobid","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/kermitt2/grobid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hdimitriou in #405: \"Docker version 18.09.2\", \"18.06.1-ce\"\r\nI am not sure it has to do with the version.\r\n\r\nI created my own Dockerfile based on yours and it works fine I think. \r\nThe difference is that i clone your repo inside the builder instead of copying folders. \r\n"}],"action":{"name":"View Issue","url":"https://github.com/kermitt2/grobid/issues/405#issuecomment-471917207"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kermitt2/grobid/issues/405#issuecomment-471917207",
"url": "https://github.com/kermitt2/grobid/issues/405#issuecomment-471917207",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hdimitriou** [comment]
0.5.4 version of Grobid

**Comment by lfoppiano** [comment]
I used to clone the repo but we have changed that afterwards so that it was possible to create the docker version of the actual version that was checked out.

**Comment by lfoppiano** [comment]
Ok it's actually a bug not in the docker but in how the grobid-service jar is built... the sub-directory of pdf.js is called build which is a very unfortunate name cause gradle is likely to ignore it. 

The issue should be fixed in the 0.5.4-fixes branch, but testing it is a pain... so might not be able to finish today.

**Comment by lfoppiano** [comment]
OK the issue is solved after 41fd74e034ee48461e5a881fc2d3b1347aec6a48 (I'm pushing the new image, might thake the whole day to upload 😓 )

**Comment by lfoppiano** [comment]
The new image pushed... 👍

**Comment by lfoppiano** [comment]
@hdimitriou could you please test it and close the ticket, if the problem is solved? Thank you!

**Comment by hdimitriou** [comment]
It works fine now, I tested the new image. 
It would be wise if you could tag it with another tag, because anyone who has already downloaded it might not download it again
