### ISSUE TITLE
DELFT based author model wrongly tags as compared to the CRF based author model

### ISSUE THREAD

**Issue by sathiyabalu89** [kermitt2/grobid#406]
Deolalikar, A.B. and Roller, L.‐H. 1989, ‘Patenting by Manufacturing Firms in India: Its Production and Impact’, Journal of Industrial Economics, vol. 37, no. 3, pp. 303–314.

**CRF based model output:**

<biblStruct xml:id="b0">
	<analytic>
		<title level="a" type="main">‘Patenting by Manufacturing Firms in India: Its Production and Impact</title>
		<author>
			<persName>
				<forename type="first">A</forename>
				<forename type="middle">B</forename>
				<surname>Deolalikar</surname>
			</persName>
		</author>
		<author>
			<persName>
				<forename type="first">L.-H</forename>
				<surname>Roller</surname>
			</persName>
		</author>
	</analytic>
	<monogr>
		<title level="j">Journal of Industrial Economics</title>
		<imprint>
			<biblScope unit="volume">37</biblScope>
			<biblScope unit="issue">3</biblScope>
			<biblScope unit="page" from="303" to="314" />
			<date type="published" when="1989" />
		</imprint>
	</monogr>
</biblStruct>

**DELFT based model output:**

<biblStruct xml:id="b0">
	<analytic>
		<title level="a" type="main">‘Patenting by Manufacturing Firms in India: Its Production and Impact</title>
		<author>
			<persName>
				<forename type="first">A</forename>
				<forename type="middle">B</forename>
				<surname>Deolalikar</surname>
			</persName>
		</author>
		<author>
			<persName>
				<forename type="first">L</forename>
				<surname>Roller</surname>
			</persName>
		</author>
		<author>
			<persName>
				<forename type="first">-H</forename>
			</persName>
		</author>
	</analytic>
	<monogr>
		<title level="j">Journal of Industrial Economics</title>
		<imprint>
			<biblScope unit="volume">37</biblScope>
			<biblScope unit="issue">3</biblScope>
			<biblScope unit="page" from="303" to="314" />
			<date type="published" when="1989" />
		</imprint>
	</monogr>
</biblStruct>

The same happened will many references, few of them are:

1. Du, C.‐J. and Sun, D.‐W. (2004) Recent developments in the applications of image processing techniques for food quality evaluation. Trends in Food Science & Technology 15, 230–249.
2. Zhu, B.‐Q., Cai, J., Wang, Z.‐Q., Xu, X.‐Q., Duan, C.‐Q. and Pan, Q.‐H. (2014) Identification of a plastid‐localized bifunctional nerolidol/linalool synthase in relation to linalool biosynthesis in young grape berries. International Journal of Molecular Sciences 15, 21992–22010.
3. Domizio, P., Lencioni, L., Ciani, M., Di Blasi, S., Pontremolesi, C. and Sabatelli, M. (2007) Spontaneous and inoculated yeast population dynamics and their effect on organoleptic characters of Vinsanto wine under different process conditions. International Journal of Food Microbiology 115, 281–289.

So is it possible to run the CRF model for author alone?

**Comment by kermitt2** [comment]
Hello @sathiyabalu89 

There is likely something missing in your example, I don't see any tags for the authors, nor any difference between what you cut and paste for CRF and DeLFT results. 

But I see the difference when testing the reference you provided:

* for CRF 

```xml
<author>
            <persName
                xmlns="http://www.tei-c.org/ns/1.0">
                <forename type="first">A</forename>
                <forename type="middle">B</forename>
                <surname>Deolalikar</surname>
            </persName>
        </author>
        <author>
            <persName
                xmlns="http://www.tei-c.org/ns/1.0">
                <forename type="first">L.-H</forename>
                <surname>Roller</surname>
            </persName>
        </author>
``` 

* for DeLFT

```xml
<author>
            <persName
                xmlns="http://www.tei-c.org/ns/1.0">
                <forename type="first">A</forename>
                <forename type="middle">B</forename>
                <surname>Deolalikar</surname>
            </persName>
        </author>
        <author>
            <persName
                xmlns="http://www.tei-c.org/ns/1.0">
                <forename type="first">L</forename>
                <surname>Roller</surname>
            </persName>
        </author>
        <author>
            <persName
                xmlns="http://www.tei-c.org/ns/1.0">
                <forename type="first">-H</forename>
            </persName>
        </author>
```
The DeLFT model labels `-H` as `<forename><forename>` instead that `<I-forename><forename>` which is a bit weird! 

In general the CRF models perform better currently than the deep learning ones, or are on par with the deep learning models. The current Deep learning models don't exploit additional features, in particular the layout features which are very important for structuring. So I would advise to stay with CRF until the DL models are improved. 

Having said that, if you want to mix, there is a mechanism to select the sequence labelling "engine" per parser/model, but there is no external configuration at model-level yet. 
If you want to force CRF or DeLFT for a parser, you need to do it programatically in `grobid-core/src/main/java/org/grobid/core/engines/tagging/TaggerFactory.java` lines **38** (the models `fulltext` and `segmentation` are already forced to CRF WAPITI even when DeLFT is selected by default):

change
```java
if (model.getModelName().equals("fulltext") || model.getModelName().equals("segmentation"))
    t = new WapitiTagger(model);
else    
    t = new DeLFTTagger(model);
 break;
```
to
```java
if (model.getModelName().equals("fulltext") || model.getModelName().equals("segmentation")  || model.getModelName().equals("name-citation"))
     t = new WapitiTagger(model);
else    
     t = new DeLFTTagger(model);
break;
```

Do the same in the file `grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java` line **634**:

```java
if (GrobidProperties.getGrobidCRFEngine() == GrobidCRFEngine.DELFT && 
            (model.getModelName().equals("fulltext") || model.getModelName().equals("segmentation") || model.getModelName().equals("name-citation")))
            extension = "wapiti"; 
```

You will see on the log:

```
INFO  [2019-03-08 21:06:24,653] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for name-header...
INFO  [2019-03-08 21:06:25,511] org.grobid.core.jni.WapitiModel: Loading model: /home/lopez/grobid/grobid-home/models/name/citation/model.wapiti (size: 436519)
```

with the expected correct result.

I will think about a yaml configuration mechanism for doing this more easily, because in the future it will make sense to mix model types when the DeLFT models will improve.

**Comment by sathiyabalu89** [comment]
Thank you for the immediate reply. It worked and results have improved. Will wait for the better DELFT models.
