### ISSUE TITLE
Accidental Crossref consolidation

### ISSUE THREAD

**Issue by bnewbold** [kermitt2/grobid#408]
I recently had an incident where I accidentally sent a large number (hundreds of thousands over a couple hours) of consolidation requests to the public Crossref API, which put excessive load on their servers. I didn't realize consolidation was enabled; i'm running an out-of-date version of GROBID and seemed to suffer from bug #300.

From my end, I have reconfigured GROBID to point Crossref requests to localhost (to ensure they don't go anywhere), and will upgrade to the most recent release. If I wanted to hit their API in bulk, I also see that I could use a proxy (to control concurrency from multiple worker machines/threads), but my intention is to do this consolidation as a later processing stage using local `biblio-glutton`.

To make debugging this sort of thing easier, I wonder if GROBID would accept patches to:

- configure a GROBID-specific user-agent header for the Crossref API requests
- configuration option to include an email address in the user-agent header (makes Crossref's operations easier)
- have a more explicit way to disable consolidation in config (eg, 'none' as an option to `grobid.consolidation.service`, and perhaps make this the default)

cc: @gbilder

**Comment by lfoppiano** [comment]
Dear @bnewbold, 
    I can answer only on part of your question 😅, indeed there was a problem that was solved in #300. Right now if you use the API without specifying any consolidation value it won't be applied by default.

To explicitly disable it, we could accept "none" in the configuration (as you propose) as consolidation method and plug in a Noop client that is selected when nothing between "crossref" and "glutton" is selected. 

My 2 cents ;-) 

Cheers
Luca

**Comment by kermitt2** [comment]
Hello @bnewbold !

Sorry for the issue with the Crossref REST API. 

Following your suggestions, with commit a01aa93c1a501a610930717066cf174121c8ba15 I've added the GROBID-specific user-agent header and the possibility to include in the header and query an email as recommended by Crossref.

This is documented here: https://grobid.readthedocs.io/en/latest/Consolidation/
 
Regarding the default settings, the gain for header metadata extraction with consolidation is now so high with the latest tuning of the matching and validation process, that I would not like to have no consolidation at all as default. It would mean that most user would simply overlook that and loose the huge benefit of consolidation. 

In the case of high scale usage, there are the "consolidate" parameters at query level to avoid consolidation - following the fix for #300, those parameters are working fine.

**Comment by kermitt2** [comment]
I still need to add the possibility to set the authorization token for the lucky subscriber of the  [Crossref Metadata Plus service](https://github.com/CrossRef/rest-api-doc#authorization-token-for-plus-service) :)

**Comment by kermitt2** [comment]
Crossref authorization token for Metadata Plus service added with commit e01592b3f6e2d0405917827d4aef52c08d4f01fb

**Comment by bnewbold** [comment]
Thank you!
Seems resolved so closing.
