### ISSUE TITLE
All table content goes to the table description

### ISSUE THREAD

**Issue by Vitaliy-1** [kermitt2/grobid#411]
This [string](https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/data/Table.java#L105) contains not only figDesc tokens but also those with tagging label `<content>`. So description includes data parsed from table cells. 
The same is true and for the [table content element](https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/data/Table.java#L132), where `<figure_head>` and `<figDesc>` are present.

**Comment by kermitt2** [comment]
Hello @Vitaliy-1 ! 

Normally it's not the case, the content part is not involved here.

Here we further parse the content and the **caption** (only) to get the bibliographical reference callout, see this [line](https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/data/Table.java#L97) . 

There's the same for figure -> https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/data/Figure.java#L304

So this string contains only the list of tokens having the same label from the application of the full text model to the captions. We are normally not mixing tokens from different structures of the tables or figure. More precisely each cluster from the clusters gives a chunk of tokens (`cluster.concatTokens()`) with the same label (`cluster.getTaggingLabel()`) relatively to the full text model applied to captions.

We are applying the full text model here to the captions, because it's the model that can identify the bibliographical reference callouts. 

Of course if upstream in the cascade of models, the table model badly annotates the `caption` field with table cell content, then we can have spurious content in the caption field. In this case it's labeling error from the table model, but the cascading process should be as expected.     

So normally it's ok I think, but I might be overlooking something - do you still see a problem?

**Comment by Vitaliy-1** [comment]
Hi Patrice (@kermitt2),

I'm testing with the default model with the set from different publishers (just to explore table parsing). It seems that this problem appears for PDFs from PLoS journals. 
To replicate:
* clone master branch
* parse [this article](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0212864&type=printable) from a batch mode: `processFullText`.
* this article has only one table and it's recognised by the default fulltext model. The table description is as follows:
```
<figDesc>Summary of aerial count survey methodology ( � denotes lack of georeferenced data).Aerial count
                    year MonthType of platform Type of count Strip width (m) % of Rift Valley sampled % of GNP sampled
                    1968 late dry season � November Fixed-wing Full count 1,000 100.0 64.7 1969 wet season � February
                    Fixed-wing Full count 1,000 100.0 64.7 1969 late dry season October Fixed-wing Full count 1,000
                    100.0 64.7 1970 wet season January Fixed-wing Full count 1,000 100.0 64.7 1971 wet season � March
                    Fixed-wing Full count 1,000 100.0 64.7 1972 late dry season October Fixed-wing Full count 1,000
                    100.0 64.7 1994 late dry season June Fixed-wing Sample count 255 4.2 2.9 1997 late dry season
                    October Fixed-wing Sample count 255 6.5 5.2 2000 late dry season October Helicopter Sample count 500
                    13.6 11.6 2001 late dry season November Helicopter Sample count 500 24.8 24.4 2002 late dry season
                    November Helicopter Sample count 500 21.4 14.6 2004 late dry season October Fixed-wing Sample count
                    303 9.9 9.6 2007 late dry season November Helicopter Sample count 500 24.7 21.9 2010 late dry season
                    November Helicopter Sample count 500 24.7 22.5 2012 early dry season May Helicopter Sample count 500
                    25.8 23.8 2014 late dry season October Helicopter Full count 500 71.8 49.9 2016 late dry season
                    October Helicopter Full count with additional sample lines outside of Rift Valley 500 73.0 53.9 2018
                    late dry season October Helicopter Full count with additional sample lines outside of Rift Valley
                    500 74.2 58.9 https://doi.org/10.1371/journal.pone.0212864.t001
                </figDesc>
``` 
For the debugging I have used list of tokens from Figure's `captionLayoutTokens` property to see attached labels:
```
token: Summary | label: <table>
token: Summary | label: <figDesc>
token: of | label: <table>
token: of | label: <figDesc>
token: aerial | label: <table>
token: aerial | label: <figDesc>
token: count | label: <table>
token: count | label: <figDesc>
token: survey | label: <table>
token: survey | label: <figDesc>
token: methodology | label: <table>
token: methodology | label: <figDesc>
token: ( | label: <table>
token: ( | label: <figDesc>
token: � | label: <table>
token: � | label: <figDesc>
token: denotes | label: <table>
token: denotes | label: <figDesc>
token: lack | label: <table>
token: lack | label: <figDesc>
token: of | label: <table>
token: of | label: <figDesc>
token: georeferenced | label: <table>
token: georeferenced | label: <figDesc>
token: data | label: <table>
token: data | label: <figDesc>
token: ) | label: <table>
token: ) | label: <figDesc>
token: . | label: <table>
token: . | label: <figDesc>
token: Aerial | label: <table>
token: Aerial | label: <content>
token: count | label: <table>
token: count | label: <content>
token: year | label: <table>
token: year | label: <content>
token: Month | label: <table>
token: Month | label: <content>
token: Type | label: <table>
token: Type | label: <content>
token: of | label: <table>
token: of | label: <content>
token: platform | label: <table>
token: platform | label: <content>
token: Type | label: <table>
token: Type | label: <content>
token: of | label: <table>
token: of | label: <content>
token: count | label: <table>
token: count | label: <content>
token: Strip | label: <table>
token: Strip | label: <content>
token: width | label: <table>
token: width | label: <content>
token: ( | label: <table>
token: ( | label: <content>
token: m | label: <table>
token: m | label: <content>
token: ) | label: <table>
token: ) | label: <content>
...
```
So the labeling here is OK. Once again, this is relevant only for PDFs from PLoS and not even for all tables. Can I do something more here to debug?

**Comment by kermitt2** [comment]
Thanks a lot @Vitaliy-1 for the detailed error, now I see the problem indeed with this table. Labelling is correct, but the table content is duplicated in the TEI serialization both in `<figDesc>` and `<table>`
 
The problem comes from the way the list of caption tokens are given to the fulltext model. There is a `processShort` method dedicated to the application of the fulltext model to short texts (abstract, captions,...). This method was actually processing all the tokens from the beginning of the list of provided tokens until the last one, even if some tokens in the middle were to be excluded.

This particular table was not working because captions was in two parts, some tokens at the beginning of the table and some tokens at the end (the table's DOI). All the tokens in the middle were considered as caption, which was a bug sorry. I added that part recently and was a bit too fast. 

Commit 99d7083d39ec34a4b6db02cba1d81cae60809932 normally solves this problem.

**Comment by Vitaliy-1** [comment]
Resolves the issue. Closing.
