### ISSUE TITLE
Is it possible to use Grobid to train on other type of document

### ISSUE THREAD

**Issue by Zhenshan-Jin** [kermitt2/grobid#423]
Hi Grobid Team,

Thanks for such a great academic paper digitization tools. A quick question is it possible to train a customized Grobid model on other types of PDF, such as report? 

Thank you,
Zhenshan Jin

**Comment by kermitt2** [comment]
Hello @Zhenshan-Jin !

Thank you for the kind words. 

It's not really possible because the labels and structures are dedicated to scientific literature. So if your reports are scientific, additional specialized training will work. Otherwise if there are other types of structures in your report, it will mean to significantly change the tool (new labels, new models, new cascade of models) and that's going beyond just retraining in term customization work.

**Comment by kermitt2** [comment]
Closing the issue - feel free to reopen if you need more info.
