### ISSUE TITLE
Failure in some recompositions of diacritics

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/grobid#47]
Grobid uses quite a lot of rules to recompose diacritics (never encoded as such in PDF), e.g.:
e' -> é

In some cases (not so frequent), the sequence of characters from the PDF is the not as expected for the existing rules and the recomposition fails. Currently the consequence is that both the "accent" and the modified charcater diseapper.

Example: for [this PDF](https://grobid.s3.amazonaws.com/Nonlinear%20CVFE%20for%20chemotaxis.pdf) (HAL Open Access)

"Clément Cancès" becomes:

    <persName>
        <forename type="first">Clément</forename>
        <surname>Canc</surname>
    </persName>

(Mac OS X Preview does not get it right neither by the way!)

**Comment by kermitt2** [comment]
Fix with commit 9e6c365df054c948bb2f396c17027f6aa125af8f and 38c95704beee62f82d4ba21916fd7ea21c9f57f4

**Comment by purker** [comment]
Hello, I have a special case regarding an acute accent. There are two tokens "NOVI´", "NOVI´" created instead of one.

xml output of pdf2xml
`<BLOCK ...>
	<TEXT ...>
		<TOKEN sid="p53_s14840" id="p53_w69">NOVI</TOKEN>
		<TOKEN sid="p53_s14841" id="p53_w70">´</TOKEN>
	</TEXT>
</BLOCK>
<BLOCK ...>
	<TEXT ...>
		<TOKEN sid="p53_s14842" id="p53_w71">C,</TOKEN>
`

In [https://github.com/purker/MethodDemosGit/blob/master/MethodDemos/output/groundtruth/TUW-200745.pdf](PDF):
'[3] HU, B. ; LEITNER, M. ; RAIDL, G. R.: Computing Generalized Minimum Span-
ning Trees with Variable Neighborhood Search. In: HANSEN, P. (Hrsg.) ; MLADE-
NOVIĆ, N. (Hrsg.) ; PÉREZ, J. A. M. (Hrsg.) ; BATISTA, B. M. (Hrsg.) ; MORENO-
VEGA, J. M. (Hrsg.): Proceedings of the 18th Mini Euro Conference on Variable
Neighborhood Search. Teneriffa, Spanien, 2005'

At first the token "NOVI" is added, then a blank " ". At the next token "´" in PDF2XMLSaxHandler:602 the last token "NOVI" is exchanged with "NOVI´", and in line 609, the last token " " is removed and "NOVI´" added again.

[NOVI, " "]
after line 602: [NOVI´, " "]
after line 609: [NOVI´, NOVI´]

I am currently working on restructuring the createTraining method in order to update the raw and feature files regarding to the corrected tei files. And this has lead to other errors, as there is an additional token.
