### ISSUE TITLE
Duplicated abstract

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#476]
I have a paper: 

[JPS081033701-CC.pdf](https://github.com/kermitt2/grobid/files/3475347/JPS081033701-CC.pdf)

and when processing the fulltext the abstract and part of the body are duplicated. In particular it looks like as the abstract, extracted 

```
    public String getHeaderFeatured(boolean getHeader,
                                    boolean withRotation) {
        if (getHeader) {
            String theHeader = getHeader();
            if ((theHeader == null) || (theHeader.trim().length() <= 1)) {
                theHeader = getHeaderLastHope();
            }
//System.out.println(theHeader);
        }
```

is basically the whole first page, however this is also extracted furhter after from the fulltext parser (`featSeg = getBodyTextFeatured(doc, documentBodyParts);` returns part of the overlapping abstract and first page). 

As a result I have the abstract and part of the first page duplicated. 

I'm wondering if there is a way to recognise when such event happens and just move everything in the body. 

In this paper there is no `abstract` mention but the layout should help recognizing the two sections

**Comment by kermitt2** [comment]
Hello ! 

This behavior has been discussed in #407 #373 #281 

This method `getHeaderFeatured()` is supposed to be removed at some point and I am not working on it anymore since many years. Transition is not very efficient as you can see with #136 which keep track of moving the the new header model (started in 2016) because it requires some time and focus. 

So it's not really an error, it's more a "compromise"/fallback due to the current weakness of the segmentation model approach to locate the header: 
- the heuristics approach (with old `getHeaderFeatured()`) still performs a bit better, so I left it as first way to identify the header zone
- using the segmentation model approach as fallback when the heuristics clearly fails also improves a bit the general accuracy, so it is used as second step
- given that we might have 2 different header zones identified, I am taking the largest ones to avoid loosing piece of the document and it might result in duplications of text (because it's better to have two times the same piece of text than one piece totally missing)

As this is basically a hack to cover the fact that we don't have enough training data for the segmentation model, I would really not spend time on hacking the hack, nor work on the old heuristics, but rather improve the segmentation model identification of the header with better  and more training data (better = using the reading order option in pdfalto).   

Maybe to put a bit more pressure on this and avoid still having the heuristics in the project, I could remove entirely the heuristics. It will result in a loss in header metadata extraction f-score of around 1-2 points (a bit more for title unfortunately), but it would help to stop coming back to this old part of the code while the segmentation model approach has been introduced to replace it. It would also avoid duplications.

**Comment by de-code** [comment]
If we think the heuristics might still produce better results on some documents, then maybe it could be a feature flag until the segmentation model is good enough?

**Comment by lfoppiano** [comment]
We could solve the problem by just understanding the overlapping between the heuristic and the probabilistic model and cut off from one of the sides. Not sure if that's possible because the layout tokens are lost in the heuristic way, if I'm not wrong.

**Comment by kermitt2** [comment]
Yes (header LayoutTokens are also used with heuristics but they are not returned, and not clear how to decide where to remove the redundant stuff) - but my point is that the time spent on this would be better used to improve the segmentation model approach so that we can throw out the damn heuristics and forget about duplicated text D.

**Comment by de-code** [comment]
Personally I'd also not want to use the heuristics anymore. My argument for a temporary feature flag would just be, to allow users to switch the heuristics back on, should they experience issues. It would also make it easier to perform evaluation of it, since everything else would be the same (whereas comparing different releases could include all sorts of changes).

I could submit a very small PR with just that flag (unless someone else wants to do it). Because it would help me already as part of #430

**Comment by kermitt2** [comment]
I initially understood the feature flag as a suggestion using the heuristics as a feature in the segmentation model :D which was also an interesting idea! 
So having a flag to disable heuristics would help to benchmark and test for sure.

**Comment by lfoppiano** [comment]
I'm testing with this document and with the header heuristic disabled, I added the option `grobid.header.use_heuristics=false`: 

[EPL0580589-CC.pdf](https://github.com/kermitt2/grobid/files/3514584/EPL0580589-CC.pdf)

and I've get quite some duplicated body parts.

**Comment by lfoppiano** [comment]
I think I found the issue (which might have been also the issue before, somehow).  

First grobid extracts header using the header model (including the abstract), but then it does the same using the fulltext parser: 

```
            // above the old version of the header block identification, because more robust
            if ((resHeader.getTitle() == null) || (resHeader.getTitle().trim().length() == 0) ||
                 (resHeader.getAuthors() == null) || (resHeader.getFullAuthors() == null) ||
                 (resHeader.getFullAuthors().size() == 0) ) {
                resHeader = new BiblioItem();
                parsers.getHeaderParser().processingHeaderSection(config.getConsolidateHeader(), doc, resHeader);
                // above, use the segmentation model result
                if (doc.getMetadata() != null) {
                    Metadata metadata = doc.getMetadata();
                    if (metadata.getTitle() != null)
                        resHeader.setTitle(metadata.getTitle());
                    if (metadata.getAuthor() != null) {
                        resHeader.setAuthors(metadata.getAuthor());
                        resHeader.setOriginalAuthors(metadata.getAuthor());
                        List<Person> localAuthors = parsers.getAuthorParser().processingHeader(metadata.getAuthor());
                        if (localAuthors != null) {
                            for (Person pers : localAuthors) {
                                resHeader.addFullAuthor(pers);
                            }
                        }
                    }
                    if ( (metadata.getTitle() != null) && (metadata.getAuthor() != null) ) {
                        parsers.getHeaderParser().consolidateHeader(resHeader, config.getConsolidateHeader());
                    }
                }
            }
            // structure the abstract using the fulltext model
            if ( (resHeader.getAbstract() != null) && (resHeader.getAbstract().length() > 0) ) {
                List<LayoutToken> abstractTokens = resHeader.getLayoutTokens(TaggingLabels.HEADER_ABSTRACT);
                if ( (abstractTokens != null) && (abstractTokens.size()>0) ) {
                    SortedSet<DocumentPiece> documentParts = new TreeSet<DocumentPiece>();
                    int endInd = abstractTokens.size()-1;
                    int posStartAbstract = getDocIndexToken(doc, abstractTokens.get(0));
                    int posEndAbstract = getDocIndexToken(doc, abstractTokens.get(endInd));
                    DocumentPointer dp1 = new DocumentPointer(doc, abstractTokens.get(0).getBlockPtr(), posStartAbstract);
                    DocumentPointer dp2 = new DocumentPointer(doc, abstractTokens.get(endInd).getBlockPtr(), posEndAbstract);
                    DocumentPiece piece = new DocumentPiece(dp1, dp2);
                    documentParts.add(piece);
                    featSeg = getBodyTextFeatured(doc, documentParts);
                    String rese2 = null;
                    List<LayoutToken> tokenizationsAbstract = null;
                    if (featSeg != null) {
                        // if featSeg is null, it usually means that no body segment is found in the
                        // document segmentation
                        String abstractText = featSeg.getLeft();
                        tokenizationsAbstract = featSeg.getRight().getTokenization();
                        if (isNotEmpty(trim(abstractText)))
                            rese2 = label(abstractText);
                        resHeader.setLabeledAbstract(rese2);
                        resHeader.setLayoutTokensForLabel(tokenizationsAbstract, TaggingLabels.HEADER_ABSTRACT);
                    }
                }
            }
```

Why is there a ```if ( (resHeader.getAbstract() != null) && (resHeader.getAbstract().length() > 0) ) {``` ? wouldn't make more sense to do so only if the abstract is empty or null?

**Comment by kermitt2** [comment]
The second part does not extract the header, it reuses the header as extracted in the first part and structure it thanks to the full text model, if the abstract is not empty.

**Comment by lfoppiano** [comment]
OK, I will check better this part. Sorry.

**Comment by kermitt2** [comment]
@lfoppiano is it possible to point to the duplicated parts in your example EPL0580589-CC.pdf, I don't see them at first look. 

[EPL0580589-CC-with-heuristics.tei.xml.gz](https://github.com/kermitt2/grobid/files/3515578/EPL0580589-CC-with-heuristics.tei.xml.gz)
[EPL0580589-CC-without-heuristics.tei.xml.gz](https://github.com/kermitt2/grobid/files/3515579/EPL0580589-CC-without-heuristics.tei.xml.gz)

In the tests, I have the abstract in the header with heuristics (which looks ok), and wrongly in the body without the heuristics, but it's hard to find other duplicated parts.

**Comment by lfoppiano** [comment]
> In the tests, I have the abstract in the header with heuristics (which looks ok), and wrongly in the body without the heuristics, but it's hard to find other duplicated parts.

Yes it's correct. I had duplicated body part when disabling the heuristics. That's why I started investigating further, I was expecting not having them. 

The issue here is actually not related to abstract anymore but more "body parts duplication", but I didn't feel like opening another issue.

**Comment by kermitt2** [comment]
Ah yes I see indeed, in the header without heuristics, we have a large part of the body duplicated :(

**Comment by kermitt2** [comment]
The issue is indeed in the re-structuring of the abstract by the full text model! The problem is not that the abstract is extracted a second time, it's the piece of document that is passed to the full text model which is not identifying the abstract correctly:

```
int posStartAbstract = getDocIndexToken(doc, abstractTokens.get(0));
int posEndAbstract = getDocIndexToken(doc, abstractTokens.get(endInd));
DocumentPointer dp1 = new DocumentPointer(doc, abstractTokens.get(0).getBlockPtr(), posStartAbstract);
DocumentPointer dp2 = new DocumentPointer(doc, abstractTokens.get(endInd).getBlockPtr(), posEndAbstract);
DocumentPiece piece = new DocumentPiece(dp1, dp2);
documentParts.add(piece);
```

In the above part `DocumentPointer dp2` is going too far and included some document part of the body :/
I have wrongly assumed that the abstract was a single DocumentPiece, so a sequence of continuous layout tokens, but some footnotes were (incorreclty) attached to the abstract and everything in the middle - all these document body sections - were passed as abstract to be structured to the full text model.

If we comment the secondary part structuring the abstract, there is no duplication. 

So the identification of the document parts corresponding to the abstract has to be a bit more fine-grained.

**Comment by lfoppiano** [comment]
Yes I was looking at it and noticed something is happening with the DocumentPointers. 

I'm wondering why are you getting the data using the documentPointer / Document Pieces instead from the abstractTokens? Is because you need the features for each token?

**Comment by kermitt2** [comment]
Yes, it's the standard input of the fulltext model (what is produced by the segmentation model), and it's a way to get easily the block features. Because the header model identifies the abstract as a list of LayoutTokens, we need to re-identify the document pointer / document piece from the layout tokens. Basically the "zones" produced by the segmentation models are list of document piece.

**Comment by Vitaliy-1** [comment]
Just leave a note here for not-to-forget that I've encountered a similar issue with duplicating abstracts and body parts and it was, most probably, related to the PDFAlto. I experimented with char sorting there before forming words, although I haven't solved it, after some manipulations, it resolved in duplicating chars rather than duplicating whole text parts. I'm planning to return to it later but I can send a PDF example if anyone is interested.
