### ISSUE TITLE
Suggestion: Allow overriding of grobid properties via environment variables

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#480]
Sometimes it would be easier being able to set grobid properties via environment variables. Especially when using Docker.

It could be similar to the way [Airflow's configuration option](https://airflow.readthedocs.io/en/stable/howto/set-config.html).

e.g. `GROBID__USE_LANGUAGE_ID` (double underscore for dot) could be translated to `grobid.use_language_id` without needing to know the available properties. Assuming all supported properties are lower case or are case-insensitive.

Alternatively `GROBID_USE_LANGUAGE_ID` could be supported, but only knowing the list of available properties (which are available in `GrobidPropertyKeys` but not for sub-projects).

/cc @kermitt2 @lfoppiano

**Comment by kermitt2** [comment]
That would be handy yes. 

In the old ages, GROBID was actually using environment variables which were overriding java properties (because it is handy!). But it was considered as bad practice for different reasons (one was security restrictions on the deployment servers of one of the main early user), and we changed that at some point so that there is no dependency to any global state (in 2012 if I remember well). 

I was actually thinking about converting the properties file into a YAML config file as I did for other project, which I find nice because it has typing and allow some structures, it can be commented, it is self-contained and so on, so much better. However maybe then typing and structures would be an issue with environment variable.

**Comment by de-code** [comment]
With Docker, many simple options are configured via environment variables because you can just pass them in, e.g. postgres database name and password. More complex configuration (e.g. nginx web config) would still be via config files. But then they have to be mounted from the host or baked into the image.

I think using a configuration file makes sense. But with the option to override them. e.g. I would need it to test it with the heuristics turned off.

I think it would still work with YAML in principal. But maybe not with the typing implementation. In the end YAML could be generated from the environment variables.

**Comment by de-code** [comment]
I've implemented the first option (see #482)
