### ISSUE TITLE
[BAD_INPUT_DATA] PDF to XML conversion failed with error code: 1

### ISSUE THREAD

**Issue by bharathgit956** [kermitt2/grobid#489]
I am trying to use grobid latest version (0.5.5) in centos based Linux server. The response from the test API http://yourhost:8070/api/version is working fine. But it is not working for full-text extraction.  The input is perfect academic document. Attaching the logs for the issue:

 'Grobid returned status {0} instead of 200\nPossible Error:\n{1}'.format(resp.status_code, resp.text))
requests.exceptions.HTTPError: Grobid returned status 500 instead of 200
Possible Error:
[BAD_INPUT_DATA] PDF to XML conversion failed with error code: 1

**Comment by kermitt2** [comment]
Hello @bharathgit956 

Thanks for the issue. The PDF parsing is failing, so the academic document might not be so perfect or there is an issue with the pdfalto binaries on your centos (less likely).

It would be nice to share this file with us to be able to reproduce the problem, otherwise it's hard to see what might go wrong. 

Could you try to do the following: 

```
>  ~/grobid/grobid-home/pdf2xml/lin-64/pdfalto  -noImage  -annotation -outline -filesLimit 2000 -blocks -noImageInline -fullFontName your_academic_document.pdf
``` 

(assuming you installed grobid at the above path and with the right PDF file name)

Is the pdfalto command working? Do you have some `.xml` files generated?

**Comment by bharathgit956** [comment]
Thank you so much for the quick response. I got the following logs. 
grobid-0.5.5/grobid-home/pdf2xml/lin-64/pdfalto: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by grobid-0.5.5/grobid-home/pdf2xml/lin-64/pdfalto)
grobid-0.5.5/grobid-home/pdf2xml/lin-64/pdfalto: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by grobid-0.5.5/grobid-home/pdf2xml/lin-64/pdfalto)

**Comment by kermitt2** [comment]
Thank you! 

Ah, it might mean that your CentOS version does not provide this version of GLIB (v15) - is it CentOS 6? Can you do:

> ldd --version

and give the version for GLIBC that is indicated?

**Comment by kermitt2** [comment]
Just to be sure, you are using a 64 bit OS right? If you type `lscpu` it should indicate 32-bit and 64-bit as CPU op-modes.

**Comment by bharathgit956** [comment]
yes. I am using a 64-bit os.  
GLIBC version is 2.12 and its CentOS 6. 
How to solve this issue?

**Comment by kermitt2** [comment]
On your side, one solution is to upgrade to CentOS 7 which has a more recent glibc - I assume your CentOS 6 is up to date, but you could do a `yum -y update glibc` to be sure.

Otherwise, in short term, I think you'd need to recompile locally pdfalto. See the project https://github.com/kermitt2/pdfalto and follow the build instruction https://github.com/kermitt2/pdfalto#build

Then you need to copy your local executable to replace the binary shipped with grobid:

> cp ~/pdfalto/pdfalto ~/grobid/grobid-home/pdf2xml/lin-64/

And you'll be fine.

For pdfalto I will see if we can rely on an older glibc version, but probably not.

**Comment by xegulon** [comment]
I also had this error, on AWS SageMaker. But I failed to build `pdfalto`

**Comment by xegulon** [comment]
I had this problem on AWS SageMaker. But your instructions worked. Thanks!

**Comment by kermitt2** [comment]
Hi @xegulon !
`Unsupported major.minor version 52.0` -> you are using a JRE version lower than the JDK that has build the jar (here 52 is JDK 1.8). You need a JRE version 8 or more to run it.
