### ISSUE TITLE
Accessing GROBID app remotely

### ISSUE THREAD

**Issue by dksanyal** [kermitt2/grobid#497]
Hi,

I would like to use the services of GROBID without installing it locally as the software is being actively developed and is frequently updated. I would like to have a script that can upload a PDF manuscript from my local machine to GROBID (the app running at http://cloud.science-miner.com/grobid/) and get the extracted information as an XML TEI file , say, in the form of a JSON response. Kindly let me know if that is possible and how to go about it.

Thanks,
Debarshi

**Comment by kermitt2** [comment]
Hello @dksanyal !

Thanks for the interest in GROBID. The documentation will answer your question:

https://grobid.readthedocs.io/en/latest/Grobid-service/

and you can use one of the client as a "script":

https://grobid.readthedocs.io/en/latest/Grobid-service/#clients-for-grobid-web-services

There's always a config file to change easily the server to be used. 

Regarding an output in JSON, you can use JsonML or other XML to Json converters adapted to XML mixed content, but you will have to do it on your own (it's a bit out of scope of GROBID, which gives an XML TEI to be transformed as required by the user and its application) - though issue #302 is dedicate to that at least for the python client. 

Finally I would like to stress that the server http://cloud.science-miner.com/grobid/ is just a demo, without any guarantees, so that people can play easily with the service. It might go down at any moment for a while, be overloaded by other users, not updated for a while too, I might switch it off when I am broke to pay the food of the dog, etc.

**Comment by dksanyal** [comment]
Thanks for your detailed response!

**Comment by kermitt2** [comment]
Closing the issue, but if you have more questions not covered by the documentation, feel free to re-open it.
