### ISSUE TITLE
DOI URL mistakenly expanded into filesystem path

### ISSUE THREAD

**Issue by bananaoomarang** [kermitt2/grobid#506]
For the paper `10.1016/j.epsr.2015.08.002` we are seeing many (~100s, so it must be an edge case particularly triggered by this paper's formatting/content) cases where a reference DOI has been expanded into a path on the local filesystem. For example:

```
<idno type="DOI">file:/localhost/home/ubuntu/grobid/grobid-home/tmp/dx.doi.org/10.1049/iet-gtd.2010.0466</idno>
```

**Comment by kermitt2** [comment]
Hi Milo! This is fixed with https://github.com/kermitt2/grobid/commit/e262107ce1db00452c9d942c9d459e995b49b219
Basically those DOI are PDF-annotations only, which should be normally "uri link" type, but apparently the prefix (protocol+host) of the links is missing and I think they are automatically solved to the local system by pdfalto. 
They are now properly handled.
