### ISSUE TITLE
Training data query

### ISSUE THREAD

**Issue by GrennanM** [kermitt2/grobid#535]
Hi,

Does Grobid contain references from PubMed within it's training data for the citation model? Or, where has the training data for Grobid come from? Appreciate any info you might be able to give on Grobid's training data.

Thanks for your help and for all your hard work on Grobid!

**Comment by Joeran** [comment]
Just to follow up on this: Is there any detailed description (in a paper or so) that explains how exactly the Grobid training data was created? Did you 'just' take data from existing datasets like Cora and PubMed, or create your own labeled dataset based on reference lists from...??? We are planning to submit a paper to JCDL (in two days). So if you could point us to more details (or provide them here) we would greatly appreciate it.

Thx
Joeran

**Comment by kermitt2** [comment]
Hello @GrennanM  and @Joeran !

Thank for the interest in Grobid.

The training data depends on the models and there are 13 models in Grobid (including 2 for patent documents). 

In general we try to focus on Open Access literature that can be reused, so CC-0 and CC-BY. This is mandatory for the training data of the segmentation model and the full text model because they include the whole article content. For models using just small excerpts of documents (like the citation model), we relaxed a bit this constraint and we are basically taking examples from any domains and sources, sometimes from copyrighted articles (using excerpts being an exception to copyrights - but this remain a minority).  

How is selected the training data? GROBID is not an academic exercise and we are more or less continuously adding training data based on reported user error cases. Regarding the citation model, we started with CORA ten years ago (if I remember well 1000 citations) but we extended several times this data set with citations mainly from articles from HAL archive and arXiv (in particular based on an effort with CERN). There's a total of 6835 annotated citations today (with 81 more in a fork to be added) and 72 segmented bibliographical section examples (for the model that segment a bibliographical section into individual citation). 

Regarding citations, PubMed and PMC sources were not particularly used, to avoid bias (only a few hundred examples I would say and probably around 10%). As we are evaluating mainly against PMC (end-to-end evaluation), we try to use very few PMC articles in the training data. 

We didn't keep track of the sources of the citations. I know it's bad from an analysis perspective but it's really painful to create training data so we keep it as lightweight as possible. 

Another thing to add regarding training data, the GROBID approach is to use very few training data carefully manually annotated and precisely aligned with PDF content, from various sources, in contrast with CERMINE or ScienceParse 1&2 which are using some massive amount of training data automatically aligned from PMC. When you see the number of training examples of GROBID for the segmentation and full-text models (respectively 148 and 25), this is interesting to see that GROBID performs at least as well than these other systems, while using several hundred or thousand times less training data. 

Finally I don't plan to write any articles about Grobid in the future, but I would like to extend significantly the documentation. Please if possible, for Grobid, cite the project repository and not any scholar articles (the crappy one I wrote in 2009 on my free time was to go on holidays at Corfu with my wife ;). For me Grobid, as a side project, is also an exercise to do things differently and to experiment beyond traditional scholar communication. Or to state it differently, the more I am trying to deal with the PDF mess, the more I am reluctant to publish anything in PDF ;)

Nevertheless, I wish you good luck for the JCDL submission and I am sorry not being able to characterize better the Grobid training data.

**Comment by Joeran** [comment]
@kermitt2  that is great. Thank you very much for the information. That is really helpful. I will cite both the repository and the paper (if I don´t cite the paper, reviewers might criticize this)
