### ISSUE TITLE
No text in boxes in "PDF reference annotation"

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#548]
I was testing the PR #533 and I found that there is a small bug in the interface "PDF reference annotation": 
![image](https://user-images.githubusercontent.com/15426/75510982-92e33200-59e4-11ea-978d-3eff10b260c3.png)

In fact when hovering over a reference identifier, it does not show correctly the reference text in the box: 
![image](https://user-images.githubusercontent.com/15426/75510955-7ba44480-59e4-11ea-853d-ac27c1d17b94.png)

**Comment by kermitt2** [comment]
Hi Luca!

It works for me, same file and ref. https://arxiv.org/pdf/0912.1391.pdf

This always worked for me (except to some small coordinates shifts due to OCR). It might be due to your tests ;)

![pdf-annotattion](https://user-images.githubusercontent.com/2340795/75541749-ca6ed000-5a1e-11ea-874a-0c6e719ed6c2.png)

**Comment by lfoppiano** [comment]
I re-tested with both Chrome and Firefox and, indeed. It works.
