### ISSUE TITLE
Recommended way of annotating line numbers

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#560]
Hi @kermitt2 

It might be good to clarify the recommended way of annotating line numbers.

I believe one of the most recent on [conversation](https://traces1.inria.fr/mattermost/inria-rookies/pl/es46rai9xtdrjpe9z9feb7riea) Mattermost:
```
I think line number could be seen as an "insert", so as a note in the segmentation model
we could imagine adding a type attribute like type="line_number" because it's very specific
ideally it could be recognized as an independent block by pdfalto, instead of having it concatenated with each line of the text - then it would be easier to cover it in GROBID without any particular ad hoc processing, just with the segmentation model which would recognized the line number as a specific area
```

I believe you also referred to the [Annotation guidelines for the 'segmentation' model](https://grobid.readthedocs.io/en/latest/training/segmentation/).

The current `<page>` numbers seem to always be present at the top level (i.e. `body` or other elements close before it). Should the same be true for line numbers?

e.g.:

```xml
<note type="line_number">1</note>
<header>The first line</header>
<note type="line_number">2</note>
<header>The second line</header>
```

You also mentioned that some line numbers might get passed to the fulltext (or header) model. And should be annotated there.

There it would be an issue if line numbers caused the current element to end, e.g. when the author name is broken over multiple lines (example: [10.1101/386813](https://doi.org/10.1101/386813)).

Should it be there like this?:
```xml
<docAuthor>First name<lb/>
<note type="other">1</note> Last name</docAuthor>
```

Or is this even wasted effort if it was moved to pdfalto? I don't really know the full scope of pdfalto. Certainly heuristics can be used to identify most line numbers (and that is what I am using to create the annotations). The position on the page is important. Sometimes there is little gap between the line number and the text though. There may be outliers.

**Comment by kermitt2** [comment]
Hello Daniel,

I plan to work on line numbers in April, for the DataSeer project in which I have booked some time for this. It will be handled first by pdfalto, basically outputting line numbers as its own block (like a column). Then I will add guidelines for this in the segmentation model and on how to handle them in other models if they unfortunately goes through (basically as we do with any noise currently). There will also be an effort for dedicated training data. 

The text/element flow form pdfalto will be different for line numbers than what it is now, so we should not consider line number with the current pdfalto output (there is one training example for the segmentation model which has line numbers right now, it will be re-annotated). The current pdfalto/grobid can not handle line number currently, it should be considered not supported, and not annotated because it would be just a hack. Normally there should be a good solution ready in May.

**Comment by de-code** [comment]
That's perfect. Thank you Patrice.

Would you prefer to keep the issue open until the annotation guidelines is updated, or track it somewhere else?

**Comment by kermitt2** [comment]
Yes let's keep this issue opened until guidelines cover that.

**Comment by de-code** [comment]
Just to let you know that I implemented an interim line number removal in https://github.com/elifesciences/grobid/pull/19
(I didn't submit a PR for hit as that's probably not going to be relevant after your solution)

**Comment by de-code** [comment]
I had to refine my implementation. In part due to there being different ways of accessing the tokens in GROBID (tokens within a block, global tokens accessed via pointers etc.). It only works with left line numbers at the moment but could be easily modified to work with both.
Let me know if you'd like me to submit a PR anyway.
If you'd like to try it, you could run:

```bash
docker run --rm -p 8070:8070 \
    --env GROBID__FEATURES__REMOVE_LINE_NUMBERS=true \
    elifesciences/grobid_unstable:fec56b74565dead8fef29ecd88a385e42c0c2403
```

**Comment by kermitt2** [comment]
So done with PR #572 in Grobid and in pdfalto with PR https://github.com/kermitt2/pdfalto/pull/93
As it is covered by pdfalto, this is also beneficial to the pdfalto users.
