### ISSUE TITLE
Bug: Ref tag with trailing right paren on version 0.6.0

### ISSUE THREAD

**Issue by KnowledgeGarden** [kermitt2/grobid#575]
This sentence
Similar results were observed among boys and girls respectively (Table S2). No significant associations

parses to
<pre>Similar results were observed among boys and girls respectively &lt;ref type="table" target="#tab_1"&gt;(Table S2&lt;/ref&gt;). No significant associations </pre>

Note the trailing paren **outside** the ref tag. This is consistent across all such instances.

**Comment by KnowledgeGarden** [comment]
There are cases where it is correct, such as
<pre>( &lt;ref type="table" target="#tab_1"&gt;Table 2&lt;/ref&gt;)</pre>
and on studying the error noted above, I described it incorrectly. It appears that the error lies in the incorrect placement of the leading paren inside the ref tag, e.g.
<pre>&lt;ref type="table" target="#tab_1"&gt;(</pre> instead of before it.
I am going to study this closer and provide a gist.

The document being processed is the pdf associated with this
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4113344/

**Comment by KnowledgeGarden** [comment]
The gist - the full Grobid output is here
https://gist.github.com/KnowledgeGarden/8241dc35a5e1fe2552a8f7f60247af3d

**Comment by kermitt2** [comment]
Hello @KnowledgeGarden and thanks for the issue !

Yes not very beutiful :)
This is due to the training data (for the "fulltext" model) which tends to not systematically put the parenthesis outside the table reference marker tags... The annotation guidelines for the training data of the fulltext model is not precise enough for this case I have to say.

We would simply need to review all the table reference callout annotations in the training data and be sure to have the parenthesis outside the annotation... what we see in the result is the actual labelling realised by the model (no post-process to clean the callout).

And we need to update the training data guidelines.

**Comment by kermitt2** [comment]
Latest fulltext model (commit af0c976b36ad17d2bb751fb588b229f1f56f2f4a) has been built on reviewed training data where those reference markers are all limited to the "key" marker, e.g. with your example:

```xml
Diet patterns and milk consuming were not different between groups (Table <ref type="table" target="#tab_0">1</ref>).
```

```xml
The associations of iodized salt and milk consumption with thyroid nodule were estimated (Table <ref type="table" target="#tab_1">2</ref>).
```

```xml
Similar results were observed among boys and girls respectively (Table <ref type="table" target="#tab_1">S2</ref>). No significant associations of thyroid nodule with UIC were observed among two age groups (Table <ref type="table" target="#tab_3">S3</ref>, Table <ref type="table" target="#tab_2">S4</ref>).
```

Trailing right parenthesis should never appear any more.
