### ISSUE TITLE
What language identifier is used for?

### ISSUE THREAD

**Issue by NLPOR** [kermitt2/grobid#588]
Hi, I noticed there a language identifier in your project, what is it used for?

**Comment by kermitt2** [comment]
Hi @NLPOR, it is used to indicate the main language of the processed PDF (for example `<text xml:lang="en">`)

**Comment by NLPOR** [comment]
Thanks, can it be used to identify the language of the raw reference?（for example <reference>清水 良 RYOU SHIMIZU,コンビナトリアルケミストリー 有機合成ロボットが化学を変える! Combinatorial Chemistry,化学 第51巻 第8号 CHEMISTRY,日本,株式会社化学同人,第51巻<reference>）

**Comment by kermitt2** [comment]
Hard to say, I don't think it can be always reliable, because the raw references are usually short and can mix languages, which makes much harder to identify the "main" language. In addition abbreviated titles are very common, and without title and just with author names and basic metadata, it's then hard even for a human. 

Now there's a confidence score associated to the classification, which help to control the result - for your example we get:

``` 
Language: ja with confidence of 0.9999999618245452
```

**Comment by NLPOR** [comment]
thanks, i also think so.
what is the methods of your language identifier, detected on char level, word level or sentence level , rules or deep learning?

**Comment by kermitt2** [comment]
We're using this language identifier -> https://github.com/shuyo/language-detection/blob/wiki/ProjectHome.md
which is a naive bayes classifier with n-gram of characters (trained on Wikipedia).

**Comment by FengXuas** [comment]
How to deal with different languages?
