### ISSUE TITLE
Raw Affiliation and Raw citation option

### ISSUE THREAD

**Issue by dominic01** [kermitt2/grobid#596]
I download the 0.6.0 zip and installed the server and noted only **Consolidated Header and Consolidate citations** options. However, when I download the got clone --branch 0.6.0, I noted two more options **Include raw affiliations and Include raw citations**.  I am also facing more crashing issues in the ZIP compiles installations  Refer: #595  .
Am I missing something?

**Comment by kermitt2** [comment]
The parameter `includeRawAffiliations` is present since version `0.6.0`. `includeRawCitations` is present since more than one year, but the tick box in the web console demo has been added recently too.

I can't reproduce your issue, both are identical for me. Using 0.6.0 zip release I have the two additional options in the web console demo. Using `git clone --branch 0.6.0 https://github.com/kermitt2/grobid`, I also have the two additional options in the web console demo. This is to be expected, the zip is built using the tags, so there should not be any differences.

**Comment by kermitt2** [comment]
@dominic01 if you have a test case about this issue, please feel free to reopen it.
