### ISSUE TITLE
Reference markers causing paragraphs and sentences to fragment

### ISSUE THREAD

**Issue by vishnudas-raveendran** [kermitt2/grobid#601]
Hi Team ,

I am trying to get sentence level extraction of text along with its coordinates. 

I have almost completed it except for the issue of reference markers within sentence breaking them down into new paragraph. For your use I am attaching the pdf used for extraction [(11 Processing Opportunities for New Advanced.pdf)](https://github.com/kermitt2/grobid/files/4852260/11.Processing.Opportunities.for.New.Advanced.pdf)  
and the clusterLabels [(ClusterLabels_refMarkerSentenceFrag.txt)](https://github.com/kermitt2/grobid/files/4852268/ClusterLabels_refMarkerSentenceFrag.txt).

**Is there someway I could overcome this fragmentation ?** 

I tried to re-train the fullText trainer without reference tag [(05_-_PMID_17035732.training.fulltext.tei.xml.txt)](https://github.com/kermitt2/grobid/files/4852250/05_-_PMID_17035732.training.fulltext.tei.xml.txt). But it gave me an error 
![image](https://user-images.githubusercontent.com/11041535/86134640-83e1cd00-bb07-11ea-8f9d-8a6847915fcc.png)

**Is the fragmentation expected? How can I correct the training error ?**

**Comment by kermitt2** [comment]
Hello @vishnudas-raveendran ! 
You have to reproduce the logic of the serialization done in the XML TEI. See https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java#L1196
There is also a special process to reconnect paragraph cut by a table or a figure if I remember well. 

Some labels like the reference markers (but also table/figure/formula markers) are "inline" mark-up, so they should belong to the current paragraph and not break it. 

Instead of working at the level of sequence labels as you are doing here I think, and re-implement what is already done and well tested in the XML result serialization, you could simply modify the existing serialization. You can easily output the coordinates of the paragraph as attribute in the XML (accumulate the LayoutToken of the current paragraph and call [LayoutTokensUtil.getCoordsString()](https://github.com/kermitt2/grobid/blob/162e83da4c845be314aa3b0fd2ac98fd93c135b5/grobid-core/src/main/java/org/grobid/core/utilities/LayoutTokensUtil.java#L165) on the list of LayoutToken to get the bounding box coordinates) and then use the XML as you want in a further process.

However there is currently no sentence segmentation in Grobid, so you would need to call a sentence segmenter when iterating over the cluster labels and serializing, based on the list of layout tokens to get offset of sentence boundaries.

**Comment by vishnudas-raveendran** [comment]
Hello @kermitt2  !
Thank you for the quick response.
Yes, I have serialised the XML and used OpenNLP's sentence-detector. See: https://github.com/vishnudas-raveendran/grobid/blob/189868300831d5d9f3e9cf5c53a1cac1f4abe545/grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java#L1234

I apologize, if you think I blotted your code. I could not find any sentence level tags in the official TEI format, so for a quick implementation, I encoded the sentence coordinate in the paragraph tag. 
![image](https://user-images.githubusercontent.com/11041535/86150773-76ced900-bb1b-11ea-84db-f9426b898be2.png)

`<p coords="[sent1_coord],[sent2_coord]">`

The resulting XML when I check if it has been correctly segmented per sentence by highlighting the sentences by alternating colours, I find that it breaks at reference markers. The snippet of resulting PDF is below

![image](https://user-images.githubusercontent.com/11041535/86151506-6d923c00-bb1c-11ea-85ac-98e809d8e984.png)


**Could you please guide me on how to avoid tagger from tagging reference markers? **

**Comment by kermitt2** [comment]
You have the element `<s>` in TEI encode sentences. 
https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-s.html

For the reference markers, you just need to follow the same logic as for paragraph: put the reference markers elements as children of the current `<s>` node and things should clean without other troubles, the ref. markers will be embedded into the current sentence.   

Personally when I segment into sentences the output of Grobid, I add as constraint that a sentence boundary cannot take place into a reference marker - this can improve significantly the quality of the reference segmentation using a reference segmenter not specialized in scientific text (avoid a sentence break in the middle of "... in Fig. C ..."). So it is useful to keep the reference markers when segmenting into sentences (it's also useful to keep reference marker labels in the label set, it improves the recognition accuracy for the other labels).

**Comment by vishnudas-raveendran** [comment]
Thank you very much.

**Comment by vishnudas-raveendran** [comment]
Hi!!

I have the `<s>` tag now with coordinates in extracted TEI file.
I had generated the required Java files as given in [TEI-encoding-of-results](https://grobid.readthedocs.io/en/latest/TEI-encoding-of-results/) page. However, it does not have the S.java file required to read the TEI file using JAXB, hence it was not reading it proper. Am I doing something wrong?

I tried generating the required file using ROMA, however, has you mentioned in above page, I am getting conflicts.

Could you please guide on how I can read the TEI file with sentence tags?

**Comment by vishnudas-raveendran** [comment]
Hi,
Update: 
Used Grobid's ODD to edit and tried to include s tag using Roma. Could not figure out in time, but could generate seg.
Since, they almost mean the same, I could make do with it for now.
Generated the required Java classes to parse the TEI XML up to seg tags.

**Comment by kermitt2** [comment]
For info PR #625 implements that with update of the XML schema for the `<s>` element.
`<ref>` are well managed and do not cause fragments, they are also used as additional constraints to avoid a sentence boundary in the middle of a reference marker.
2 sentence segmentation methods are supported: openNLP sentence detector and the great [Pragmatic Segmenter](https://github.com/diasks2/pragmatic_segmenter)  (fast and good on scientific literature).
To get coordinates for the sentence, simply add "s" in the list of requested coordinates at query time.

**Comment by vishnudas-raveendran** [comment]
Thank you
