### ISSUE TITLE
Demo server service unavailable

### ISSUE THREAD

**Issue by sdf1444** [kermitt2/grobid#611]
Hi

I want to use the demo server for testing in my application but currently the server seems to be unavailable. Would you be able to turn it back on so that I can use it.

Thanks

**Comment by lfoppiano** [comment]
Hi @sdf1444 the service seems working fine. What is it the problem?

**Comment by sdf1444** [comment]
> Hi @sdf1444 the service seems working fine. What is it the problem?

Hi was wondering if you can change it to https because my heroku app does not accept an http request only https request from this url.

Thanks

**Comment by kermitt2** [comment]
Hello, the demo server is just a demo and should be understood as such. It is without any guarantees, so that people can play easily with the service, but it might go down at any moment for a while, it is frequently overloaded by users, not updated for a while too, and I might switch it off when I am broke to pay the food of the dog, etc. 

For actual work with Grobid you need to deploy your own instance of the service, which is normally very easy.
