### ISSUE TITLE
Suggestion: Separate Reference Consolidation Service

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#617]
It would be good to separate the reference consolidation from the extraction itself (I believe there is no such service yet?).

Some of the advantages I could see with that:

### Consolidation Results Used As Suggestions

The consolidation is not perfect (nothing is of course, #616). By using it as a separate service it would make it easier to see it as suggestion. For example a user could accept those manually. Or they could be accepted automatically depending on how confident we are in the results.

An alternative to that could be to include original and consolidated XML in the response.

### Consolidation as a Background Process

The extracted results could initially be used directly which will be quicker. Consolidation could happen in the background and later enhance the results.

### Backdated Consolidation

The consolidation could be used on XML that had already been extracted before (or may not even come from GROBID).

### Better API Progress Feedback

Even if say a website wants to extract and consolidate in one go, it could give better user-feedback by splitting the process. e.g. a user could see that it has been extract and is now currently being consolidated. If consolidation fails, it could be retried etc.

**Comment by kermitt2** [comment]
Thanks Daniel ! 

I think this is already the case, one can select crossref or biblio-glutton for consolidation in the config. file. Consolidation is a background process as it relies on external services and run with a distinct pool of threads (in the case of crossref, the number of parallel queries follows the dynamic max query per second returned by the service).
 
It's also possible to simply use biblio-glutton separately for consolidation, and even call grobid from biblio-glutton if we start from a raw reference string. Some Grobid users like scite.ai are using it like that, to optimize the balance between all the services, because consolidation takes actually more runtime than Grobid itself, so it's good to have more biblio-glutton nodes for instance than grobid nodes if one wants to scale (crossref becomes quicly impossible to use if we want to process several PDF in parallel, because the limit of queries per second - even in the best hours/days - is a blocker). 

I also used it like that for ISTEX, running Grobid without consolidation, then call the consolidation based on the XML and updating the XML. In general it's really up to the user to build its pipeline according to its needs, as you suggest.

**Comment by de-code** [comment]
Okay, thank you.

I see, I think I was wrongly assuming that biblio-glutton was always meant to be used through GROBID.

I see the value of biblio-glutton, but it seems quite a bit of setup (but I may be wrong). Having the option to start with using Crossref would be good.

I haven't studied `biblio-glutton` yet. Can it be used directly with Crossref or does it need to build the index? Does it need to use ElasticSearch?

**Comment by kermitt2** [comment]
Yes biblio-glutton requires an heavy set-up, that's the price to pay ;) 
The idea is not to use and not to depend on CrossRef REST service, no compromise on this ! 

You can test/play with biblio-gluton at the public demo end point:  

http://cloud.science-miner.com/glutton/service/data

for example:

http://cloud.science-miner.com/glutton/service/lookup?biblio=koff%2027%201994%20cell&firstAuthor=koff&jtitle=cell&firstPage=27&postValidate=true

**Comment by de-code** [comment]
Okay, thank you again.
Nothing is free these days ;-)

I probably should not use the demo service to do the evaluation on my documents.

I better close this issue.

**Comment by kermitt2** [comment]
I added a faq label, so I re-open until we put this in the faq :)

**Comment by lfoppiano** [comment]
Not super-relevant, there is another label called "documentation", if it's the same, we could merge with "Faq"? (the black colour is threatening btw 😂)

**Comment by kermitt2** [comment]
ah yes sorry! black was the last "color" not already taken. I remove it.

**Comment by kermitt2** [comment]
I close this issue, this is already documented in details [here](https://grobid.readthedocs.io/en/latest/Consolidation/)
