### ISSUE TITLE
Failed to run on Google Cloud Run (tini error)

### ISSUE THREAD

**Issue by ranihorev** [kermitt2/grobid#656]
Hey,
I'm trying to run the docker image on Google Cloud Run but, unfortunately, it fails to start due to an error in TINI.
```
[FATAL tini (1)] PR_SET_CHILD_SUBREAPER is unavailable on this platform. Are you using Linux >= 3.4
```
Any ideas for how to fix this?
Thanks!

**Comment by kermitt2** [comment]
Hello !

Basically this version of Linux is not supported by tini.
tini is used to ensure that pdfalto processes when running docker are not becoming zombies.

The best is to use a supported linux version (so not too old... did you consider more recent Linux distrib for your VM?).

An init process is necessary for the Grobid container, because it is using multi-process. If you can't use a more "modern" linux, you can try to change tini with another init process: see https://ahmet.im/blog/minimal-init-process-for-containers/ but I never tried anything else, so I can't really help.

**Comment by ranihorev** [comment]
Thanks for the quick reply!
I'm using [Google Cloud Run](https://cloud.google.com/run) for the first time, and so far I wasn't able to find a way to pick the Linux distro. From the docs it seems like it's using [gVisor](https://cloud.google.com/run/docs/reference/container-contract#sandbox) and `prctl` is [not fully supported](https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/).

What do I need to do to replace tini?

**Comment by ranihorev** [comment]
Closing the issue. For future reference:
```
RUN apt install dumb-init
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
```
