### ISSUE TITLE
Docker Grobid service maintains high memory usage while idle

### ISSUE THREAD

**Issue by amcraig** [kermitt2/grobid#704]
Hi all, 
I've been running Grobid with docker using the same command in the documentation:
`docker run -t --rm --init -p 8070:8070 -p 8071:8071 lfoppiano/grobid:0.6.1`

After Grobid receives the API call to process 8 papers the memory usage will increase to ~5 GB as expected, but after the API response has been returned, `docker stats` still states that it has not freed the memory back to the system and stays allocated at ~5 GB.

Is this expected? This seems like an issue to me as I would have expected the memory to be freed after Grobid finishes processing papers. Is this to save having to reload the models into memory on the next batch of API calls?

**Comment by kermitt2** [comment]
Hello! This is the expected behaviour. Loading all the models take around 30s so we don't want to do it at each call and we keep the service "warm". There is also no notion of "batch" of API calls - the service is always ready (stateless) to process incoming documents, as long threads are available in the pool of threads.

**Comment by amcraig** [comment]
Got it! Really appreciate the explanation.
I'll close the ticket.
