### ISSUE TITLE
Possible use cases of GROBID without service instance? 

### ISSUE THREAD

**Issue by yassinetb** [kermitt2/grobid#708]
I'm trying to use this for a side-project and setting up a server dedicated to GROBID is too computationally expensive for very few use cases. Is it possible to use GROBID TEI extractor as an isolated function which we'd only call when needed, so that is without an instance of GROBID service running?  

Thank you!

**Comment by kermitt2** [comment]
Hello @yassinetb !
See https://github.com/kermitt2/grobid#demo

**Comment by yassinetb** [comment]
> Hello @yassinetb !
> See https://github.com/kermitt2/grobid#demo

Thank you @kermitt2 for your quick response. I am aware of the demo and have used it for testing purposes. I should have made it clear in my comment that this is for production code, so using the demo is not really feasible. The reason I said "very rare use" is because I am realistic about how many people will actually use my app 😅😅😅

**Comment by kermitt2** [comment]
Ah I see ! 

Well the batch call would be very likely a terrible solution for a case by case usage, because it takes 30s to load the model... 

Maybe on a machine with plenty of swap memory, the service could remain in memory, but in practice in the swap... calling the service would be slower but still much faster than an external command call to the batch?
