### ISSUE TITLE
Hardware Specs for running the service

### ISSUE THREAD

**Issue by samanyougarg** [kermitt2/grobid#735]
Hi,

What hardware specs does the machine that cloud.science-miner.com/grobid/ is running on have?

We have deployed the docker container on an AWS c5.xlarge instance (4vCPUs and 8GB RAM) but it is taking more than a minute to process (`processFulltextDocument`) individual PDFs with like 5-10 pages whereas the hosted service is able to achieve the same in less than 5 secs.

**Comment by kermitt2** [comment]
Hi @samanyougarg !

The demo on science-miner runs on a Linode instance 6 CPU Cores, 16 GB RAM together with another demo and it hardly uses more than 6GB in total. I am not using a docker container, but on another deployment I did and I had very similar performance.  

Maybe such a super long runtime might be due to the consolidation option set for all extracted bibliographical references? If CrossRef is used, it happens that their API is lagging and with many reference to match, it's possible that we have something very slow from time to time. 
 
I have never used a AWS instance with grobid myself, but other Grobid users are and they got usually faster runtime than the science-miner demo, because their machine doesn't host other services.

**Comment by samanyougarg** [comment]
Thank you very much for the quick reply @kermitt2!

I am using the docker image without any change and don't think I have consolidation option set for all extracted bibliographical references. 

Thank you for letting me know. Will test on a different server again with/without docker.

**Comment by samanyougarg** [comment]
Quick update: I installed the service using the docker container on a Digital Ocean CM with 4vCPUs and 8GB RAM. It is working well now.
