### ISSUE TITLE
Training header model

### ISSUE THREAD

**Issue by igor261** [kermitt2/grobid#748]
Hello,

I was wondering how the training of the header model is performed.

Is the resulting model built on the already trained header model or is it built from scratch?

Best regards,
Igor

**Comment by kermitt2** [comment]
Hello @igor261 !

Training is "from scratch". Models obtained via incremental learning are less accurate than when trained from scratch for CRF and RNN-style models. 

For SciBERT-CRF models (not shipped with GROBID because too large, they have to be trained via DeLFT), so far I am doing the usual fine-tuning from the original SciBERT model, without any pre-retraining or post-retraining.
