### ISSUE TITLE
Loading only the required models

### ISSUE THREAD

**Issue by rohittilwani** [kermitt2/grobid#749]
Hi,

I am trying to run grobid for one of my projects, but falling into memory issues due to limited ram.
I need to identify authors title and sections of the pdf but don't need references, citations and figures model. If I remove the models from "grobid-home/models", it throws an error while running due to unavailability of model. 

I wanted to know if there is a way to keep these models from loading with the help of any config file or defining what models to load. Also, is this a correct assumption that most of the ram grobid uses is consumed by "grobid-home/models"? If not, is there some way to optimize ram usage of grobid?

Thanks in advance. :)

**Comment by kermitt2** [comment]
Hi @rohittilwani  !

There's a lazy loading mechanism of the models but it's not going to help in your use case, because the loading is triggered by the usage and occurrence of structures in the documents to be processed. 

So for your specific case, there's nothing available, except modifying the code to avoid calling the corresponding parsers in the fulltext parser (https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java#L123).

> Also, is this a correct assumption that most of the ram grobid uses is consumed by "grobid-home/models"? If not, is there some way to optimize ram usage of grobid?

The largest amount of RAM is likely consumed by the PDF parser, but then yes the models. However, the largest models are the ones you will anyway need (segmentation, header, fulltext), so it's not sure that it will be enough to ignore the other ones for solve your RAM issues. 

The RAM usage in GROBID is already optimized in the default settings, usually RAM usage increases by changing the default :)

**Comment by rohittilwani** [comment]
Hi @kermitt2 ,

Thanks a lot. I will disable the parser calls not relevant to my case.
