### ISSUE TITLE
Failing GROBID build using Gradle (MacOS Big Sur)

### ISSUE THREAD

**Issue by felixwallis** [kermitt2/grobid#763]
I haven't been able to build GROBID with Gradle as instructed in the documentation due to the following error.

<img width="1439" alt="Screenshot 2021-05-28 at 11 40 28" src="https://user-images.githubusercontent.com/63267551/119971969-8c59b680-bfa9-11eb-9702-98f31e7d59ee.png">

I'm building GROBID via the following steps:

- Downloaded and unzipped GROBID into ~/Desktop/pdf_summary
- Tried to build GROBID using ./gradlew clean install per documentation. 

Environment:

- macOS Big Sur Version 11.3.1 (Apple M1 Chip)
- Java version "16.0.1" 2021-04-20
- Java(TM) SE Runtime Environment (build 16.0.1+9-24)
- Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
- Gradle 7.0.2

**Comment by kermitt2** [comment]
Hello Felix

Thanks for the issue and the clear description of your environment. 

From the [documentation](https://grobid.readthedocs.io/en/latest/Install-Grobid/#getting-grobid):

> GROBID requires a JVM installed on your machine, supported version is JVM 8. Most recent JVM version (up to JVM 11) will work correctly. CRF models will also work with JVM up to 14, but using the Deep Learning with JVM beyond 11 will lead to issues. 

The Gradle version defined in Grobid (6.5.1) is not compatible with Java 16. You can either update Gradle to 7.0 in `grobid/gradle/wrapper/gradle-wrapper.properties` (but never tested!) or use an older JVM (my advise). Note that if you want to use the Deep Learning models, for the moment you need a JVM below version 11 (included) due to additional security to the JVM (issue #688).

**Comment by felixwallis** [comment]
Thanks for the advice!
Updating to Gradle 7.0 unfortunately failed, so I decided to run using Docker, which worked well.

**Comment by felixwallis** [comment]
Also got to work using JVM 8.
