### ISSUE TITLE
Error: No DeLFT egine

### ISSUE THREAD

**Issue by Jastolfo** [kermitt2/grobid#802]
WARN  [2021-07-21 12:31:50,808] org.grobid.core.utilities.GrobidProperties: No configuration parameter defined for DeLFT engine for model fulltext
WARN  [2021-07-21 12:31:50,808] org.grobid.core.utilities.GrobidProperties: No configuration parameter defined for DeLFT engine for model segmentation
INFO  [2021-07-21 12:31:50,808] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 9/10
86.2.41.125 - - [21/Jul/2021:12:31:50 +0000] "POST /api/processFulltextDocument HTTP/1.1" 500 86 "-" "python-requests/2.25.1" 21951
WARN  [2021-07-21 12:31:54,153] org.grobid.core.utilities.GrobidProperties: No configuration parameter defined for DeLFT engine for model fulltext
WARN  [2021-07-21 12:31:54,153] org.grobid.core.utilities.GrobidProperties: No configuration parameter defined for DeLFT engine for model segmentation
INFO  [2021-07-21 12:31:54,153] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 10/10

This is the respond I get on using python to request a paper. What do you think about this issue?

**Comment by kermitt2** [comment]
Hello @Jastolfo !

It's not an issue, just a warning message that there is no configuration parameters set for the fulltext and segmentation deep learning models in the config file. These DeLFT models are anyway not present currently in the github project (RNN segmentation is performing significantly lower than CRF, and fulltext has too large input sequence sizes), so no need for parameters for the moment because the CRF models are always use for them.

**Comment by Jastolfo** [comment]
Thank you
