### ISSUE TITLE
[Gradle] Cannot create parent directory for lock file 

### ISSUE THREAD

**Issue by starsareintherose** [kermitt2/grobid#817]
```
Exception in thread "main" java.lang.RuntimeException: Could not create parent directory for lock file /root/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1-all.zip.lck
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

**Comment by lfoppiano** [comment]
Dear @starsareintherose, the problem seems related to your installation, rather than to grobid. Could you please share more information about your environment?

**Comment by starsareintherose** [comment]
Actually, I am trying to put this repo to AUR (Arch Linux), so I write a PKGBUILD (similar to Shell script) to help more people to install it.
My PKGBIULD is here. and All the files are attached.
```
# Maintainer: Malacology <guoyizhang at malacology dot com>
# Contributor: Malacology <guoyizhang at malacology dot com>

pkgname=grobid
pkgver=0.7.0
pkgrel=1
pkgdesc="A machine learning software for extracting information from scholarly documents"
arch=('any')
url="https://github.com/kermitt2/grobid"
conflicts=('grobid-git')
license=('Apache-2.0 License')
depends=(
	'java-runtime'
)
source=("https://github.com/kermitt2/grobid/archive/$pkgver.zip")
sha256sums=('SKIP')

package() {
  install -dDm755 "$pkgdir"/usr/{bin,share/grobid}
  cd $pkgname-$pkgver
  mv * $pkgdir/usr/share/grobid
  cd $pkgdir/usr/share/grobid
  chmod +x *
  ./gradlew clean install

}
```

**Comment by starsareintherose** [comment]
error log is here.
```
░▒▓ ~/Dow/Grobid ▓▒░ makepkg    ░▒▓ ✔  14:07:46 ▓▒░
==> Making package: grobid 0.7.0-1 (Tue 17 Aug 2021 14:08:39 CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found 0.7.0.zip
==> Validating source files with sha256sums...
    0.7.0.zip ... Skipped
==> Extracting sources...
  -> Extracting 0.7.0.zip with bsdtar
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
Exception in thread "main" java.lang.RuntimeException: Could not create parent directory for lock file /root/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1-all.zip.lck
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by lfoppiano** [comment]
Hi, are you running the command as root? Cause the error seems to indicate that the process cannot create a parent directory under `/root/.gradle`. The `./gradlew` command is downloading the gradle jar, and it seems it's not able to extract it. 

Minor remark, I think that you could do: 
`chmod +x gradlew` rather than `chmod +x *`

**Comment by starsareintherose** [comment]
That's so strange, the shell script in `package() { }` is running as fakeroot.

**Comment by lfoppiano** [comment]
Well, in principle this issue is not related to grobid. I cannot really help on arch Linux, perhaps you could check why such directory cannot be created

**Comment by michaellass** [comment]
> That's so strange, the shell script in `package() { }` is running as fakeroot.

You are on the right track here. Since `package()` runs as fakeroot, `$HOME` is set to `/root`. `gradlew` attempts to work inside of `/root` and fails.

A solution is to run `gradlew` in the `build()` function. However, I think there are more changes needed to make the `PKGBUILD` work properly:
* You also want to set `GRADLE_USER_HOME=${srcdir}/gradle` or something like that so that makepkg does not mess with the user's home.
* A path to the local m2 repository needs to be specified as well and grobid will be installed there.
* gradle is currently used in version 6.5.1. This only support Java up to version 14. According to the documentation (https://grobid.readthedocs.io/en/latest/Install-Grobid/), grobid itself requires something between Java 8 and 11. So you need to adjust the dependency and make sure that a suitable java version is used for building (e.g. using archlinux-java-run).
* gradle should probably be launched with `--no-daemon` so that no running daemon is left behind.
* For building, I assume that a JDK is required and a JRE is not sufficient. So you need a build dependency on java-environment.
* The license should simply be "Apache" because it can be found under that name in the license package.

Here's a suggestion, however you still need to implement the `package()` function. I have no idea what needs to be installed and what not. You find the jars in `${srcdir}/m2`.

```bash
# Maintainer: Malacology <guoyizhang at malacology dot com>

pkgname=grobid
pkgver=0.7.0
pkgrel=1
pkgdesc="A machine learning software for extracting information from scholarly documents"
arch=('any')
url="https://github.com/kermitt2/grobid"
conflicts=('grobid-git')
license=('Apache')
depends=(
	'java-runtime<=11'
	'archlinux-java-run'
)
makedepends=(
	'java-environment<=11'
)
source=("https://github.com/kermitt2/grobid/archive/$pkgver.zip")
sha256sums=(31c48f63d013e7be6731cbc3fa5c872af82d9c9b871ed422bbc5d9fca512297a)

build() {
  export GRADLE_USER_HOME=${srcdir}/gradle
  export JAVA_HOME=$(archlinux-java-run -b 11 -f jdk -j)

  mkdir -p "${srcdir}"/{gradle,m2}

  cd $pkgname-$pkgver
  ./gradlew --no-daemon -Dmaven.repo.local=${srcdir}/m2 clean install
}

#check() {
#  export GRADLE_USER_HOME=${srcdir}/gradle
#  export JAVA_HOME=$(archlinux-java-run -b 11 -f jdk -j)
#
#  cd $pkgname-$pkgver
#  ./gradlew --no-daemon -Dmaven.repo.local=${srcdir}/m2 cleanTest test
#}

package() {
  true
  # to be written
}
```

**Comment by bnewbold** [comment]
If you are packaging GROBID to run as a service, you might also want to package a distro-specific configuration file and init file.

In particular, GROBID (via pdfalto, I think) needs to write to disk when parsing PDF files. I've found it works best to have this temp dir be a ramdisk. Using `systemd` / `tmpfiles.d`, I install a file like this, then point to it from both `TMPDIR` (as an init environment variable for the daemon) and the YAML configuration file.

```
#Type Path        Mode UID  GID  Age Argument
d    /run/grobid/tmp   0755 {{ grobid_user }} {{ grobid_user }} 10d -
```

(where `grobid_user` is a template)

I don't run Arch, and do this installation via ansible, but it might be relevant.

**Comment by swapnilakubattin09** [comment]
Click Gradle Settings to go to gradle configuration page

<img width="498" alt="Screenshot 2023-08-09 at 2 17 01 PM" src="https://github.com/kermitt2/grobid/assets/140517515/0355c68e-2cdf-48f8-9dce-73a84a670886">

Change gradle user home to empty.
so I changed gradle configuration to its default position, which is empty , and that fortunately fixed the problem.

I don’t know and want to know the exact underlying causes, just to take a note about the fix.
