### ISSUE TITLE
GROBID citation parsing issues, for possible training

### ISSUE THREAD

**Issue by bnewbold** [kermitt2/grobid#847]
I have recently started using the `parseCitationList` endpoint to parse raw citation strings from the Crossref citation metadata, included in the Crossref API and bulk metadata dumps. Many citations are already parsed and/or matched to specific DOIs, either by the original publisher or by Crossref themselves. My goal is to do additional parsing and matching, especially to works which do not have DOIs (like arxiv pre-prints, conference proceedings, books, etc). This initial batch are mostly English language references, to English language works. Overall, GROBID is working really well for this task.

When doing hand evaluations, I took notes on some issues parsing with GROBID, and they are available here: https://gist.github.com/bnewbold/b437e363e6a0429719c65c751babe84d

Some of the challenges here are issues with the citation strings themselves (like OCR problems). Some of them I suspect are due to missing entries in the `grobid-home` lexicon lists (like non-European author surnames). And some are corner cases not parsed well (yet).

If I manually tag a subset of these in TEI-XML, and submit a MR to include them as training data in `./grobid-trainer/resources/dataset/citation/corpus/` and/or `grobid-trainer/resources/dataset/name/citation/corpus`, would that be a helpful contribution to the project, or would it just create a bunch of review work?

**Comment by kermitt2** [comment]
Thank you @bnewbold , this is such a great effort and so useful ! 

This is exactly what is needed to improve Grobid, there are many citation patterns missing from the current training data. 

You are very welcome to manually label some examples corresponding to the cases you identified. We might want to improve the [annotation guideline for the citation model](https://grobid.readthedocs.io/en/latest/training/Bibliographical-references/) for the cases not covered. In any case, any annotations are reviewed (because two pairs of eyes are always better), but it's not a problem.

**Comment by bnewbold** [comment]
I took a first pass at annotating these: https://github.com/kermitt2/grobid/pull/854
