### ISSUE TITLE
TEI-XML output: un-escaped ampersand ('&') in ISSN <idno> tag

### ISSUE THREAD

**Issue by bnewbold** [kermitt2/grobid#848]
When parsing this raw citation string with `processCitation` or `processCitationList`:

```
Maheswari, S., Vijayalakshmi, C.: Optimization Model for Electricity Distribution System Control using Communication System by La-grangian Relaxation Technique. CiiT International Journal of Wireless Communication 3(3), 183–187 (2011) (Print: ISSN 0974 – 9756 & Online: ISSN 0974 – 9640)
```

The output XML contains a parsed ISSN `<idno>` tag like:

```
<idno type="ISSN">0974 - 9756 & Online: 0974 - 9640</idno>
```

The ampersand character is not escaped, which makes the entire XML snippet invalid. It should be a `&amp;`. If the raw citation is returned, the `<note>` tag is escaped correctly:

```
<note type="raw_reference">Maheswari, S., Vijayalakshmi, C.: Optimization Model for Electricity Distribution System Control using Communication System by La-grangian Relaxation Technique. CiiT International Journal of Wireless Communication 3(3), 183–187 (2011) (Print: ISSN 0974 – 9756 &amp; Online: ISSN 0974 – 9640)</note>
```

It looks like the problem is missing `TextUtilities.HTMLEncode()` around here: https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java#L2646

for both ISSN and ISSNe outputs. I can provide a patch if it would be helpful

The ISSN also isn't validated, and includes two ISSNs, but that is a separate more complicated issue.

**Comment by bnewbold** [comment]
From a quick scan, it looks like these other fields are also not escaped in the same file; this might not be an exhaustive list:

- `HALFile` (`url`)
- `HALid` (`uri`)
- <keywords scheme="hal"> (`subject`)
- `<keywords type="subject-headers">` (`keywords1`)
- `<idno>` (`uri`) when uri startsWith "http://hal."
- `town` and `country` in the context of `<meeting>` (line 2437)

**Comment by kermitt2** [comment]
Yes we should escape all these fields too, because garbage in/garbage out ! 

> The ISSN also isn't validated, and includes two ISSNs, but that is a separate more complicated issue.

Yes, two ISSN is super rare. In general I think ISSN are not used a lot in actual references. I am not even using ISSN for matching in biblio-glutton, because I had errors from them (I think it is related to the problem of changes of ISSN for the same journal over time, there is no guarantee in CrossRef that we use an updated ISSN or the historical ISSN at the moment of publication).

**Comment by bnewbold** [comment]
Yeah, agree that ISSN is rare, and even when it exists the "continued as" situation with some journals is extra complexity.

**Comment by bnewbold** [comment]
I went back and checked the status of old v0.5-era GROBID processing attempts on tens of millions of PDFs, and found one more pattern of unescaped XML: `<label>` with raw affiliations. I updated the PR with a test case and patch. It is possible that when re-processing with v0.7.x more cases will crop up, but I think the PR is a good start.

**Comment by kermitt2** [comment]
I checked in other TEI serialization places, and found a couple of additional possible missing unescaped cases (mostly not used or for patent number stuff), which are covered too now. In the more recent development, I was using XOM to serialize XML, which solves this problem of course, but I didn't find the courage/time to update all the old serialization (which is working fine otherwise).
