### ISSUE TITLE
Single file JAR

### ISSUE THREAD

**Issue by Phyks** [kermitt2/grobid#88]
Hi,

[Cermine](http://cermine.ceon.pl/), a similar tool, is offering a single file JAR, with every dependences embedded in it: http://maven.icm.edu.pl/artifactory/simple/kdd-releases/pl/edu/icm/cermine/cermine-impl/1.8/ (and see https://github.com/CeON/CERMINE#using-cermine, executable JAR part) (which is also directly callable on PDF file or folders).

I do not know much about the JAR format and the way Java app can be distributed, but it would be really cool to have the same feature for Grobid, allowing to redistribute easily in non Java apps.

I found https://search.maven.org/#search|ga|1|grobid but I am not sure what is included in the JAR files, especially grobid-home seems to be almost empty.

Thanks

**Comment by kermitt2** [comment]
Hello!

There are reasons for having both a jar and a separate resource "home" directory. GROBID uses native libraries to speed up the PDF parsing, the CRF processing and to be more robust. The first version of GROBID was using PDFBox and Mallet (so it was avalaible in a single jar file) like CERMINE, but the robustness, the speed and the required amount of memory of these libraries were really a blocking issue. One goal of GROBID for header extraction was to run under one second in average for PDF to allow "interactive" applications. 

Using the fast native libraries (xpdf, Wapiti) makes necessary the "home" directory, because even with JNI some resources cannot be loaded within the JAR. Another reason is that in the current implementation choice, the pdf parsing runs in a separate process which makes the overall more robust (no JVM crash even for super ill-formed PDF).    

So regarding the balance between performance and ease of packaging, GROBID is proritizing the first. It remains very easy I think to integrate GROBID as a REST service in particular for non java applications, and it takes advantage of multithreading without anything more to do. 

The maven artefact does not inlude the zip Grobid home directory (build by maven) so it is still necessary to add it. 

If a critical requirement is to have a single jar, CERMINE is indeed a good alternative!

**Comment by Phyks** [comment]
Ok, Thanks for the detailed explanations on this point. I think I will head to CERMINE for this particular project which is meant to run directly on the end user computer. However, I will keep an eye on Grobid as it is, indeed, much faster than CERMINE, and would be really useful for hosted projects.

Thanks!
