### ISSUE TITLE
Extracting only full text and sections structure?

### ISSUE THREAD

**Issue by kleag** [kermitt2/grobid#900]
Hi,

My question is probably similar as #749 but a little bit different. I have technical documents (requirements) that are not scientific articles. They contain some kind of references but at first approximation, I just have to extract the full text and, possibly, the sections structures. Do you think that grobid is usable for this task? Maybe a full retraining would be necessary? 

If you think that grobid is not the good choice for this task, maybe are you aware of other possibilities? I did not find good alternatives, except for pdftotext, but this one will not extract the sections structure.

Thanks for you attention.

**Comment by kermitt2** [comment]
Hi @kleag 

For non-scientific - but technical - documents, we need typically to change the segmentation model to take into account a different type of general "organization" of the document "zones" and the header model to extract the metadata specific to the new document type. The rest could be reused (e.g. the reference identification and resolution mecanism, the parsing of section header, paragraphs, figures, etc.), because it's still technical and scientific text content. 

In another work that could not be opened, I extended for example Grobid to standards (e.g. IETF, 3GPP, ISO...) by changing these two models, and even with very few examples, it was working very well.  In this grobid fork, I added a mechanism to manage custom models (called "flavors") and standard models. I started to add it to the normal grobid version, but it's still a work in progress... it would also answer your need I think.

I am not aware of alternative with similar fine-grained structuring as Grobid for this, but you could try maybe https://github.com/axa-group/Parsr which is quite generic.

**Comment by kleag** [comment]
Hi @kermitt2 ,

Thanks a lot for your detailed answer. I must apologize because in fact the structure of my document was really correctly extracted. I have been deceived by the complex (for me) xml and by the fact that a lot of things have been wrongly analyzed as bib references. As you can see in the attached pdf, there is a lot of things like "[56s278-R]" that the default grobid identify as bib refs. 

But as I am here only interesting in paragraph structure, the current output of grobid should be perfectly usable. In a second time, I could work on metadata extraction but I can mainly receive it from the DMS. 

> I am not aware of alternative with similar fine-grained structuring as Grobid for this, but you could try maybe https://github.com/axa-group/Parsr which is quite generic.
Thanks for this reference. I did not find it. I'm giving it a try currently.

[one_page.pdf](https://github.com/kermitt2/grobid/files/8408389/one_page.pdf)
