### ISSUE TITLE
Timeout/Error when processing an MDPI PDF

### ISSUE THREAD

**Issue by mazzespazze** [kermitt2/grobid#905]
Hello!

I successfully deployed a grobid-server and I was parsing some articles. Everything was smooth until I found this paper: https://www.mdpi.com/2076-3921/11/2/251

I downloaded its PDF and tried to parse it with the following command:
`curl -v --form input=@./mdpi_article.pdf localhost:8070/api/processFulltextDocument`
And I get an XML with the following content:
`[TIMEOUT] PDF to XML conversion timed out`

When trying instead the `processHeaderDocument` command, everything works as expected and the article headers (title, abstract, etc.) gets parsed in a good way. 
`curl -v --form input=@./mdpi_article.pdf localhost:8070/api/processHeaderDocument`

This is the error I got:
```
ERROR [2022-04-06 14:07:25,987] org.grobid.core.process.ProcessPdfToXml: pdfalto process finished with error code: 143. [/opt/grobid/grobid-home/pdfalto/lin-64/pdfalto_server, -fullFontName, -noLineNumbers, -noImage, -annotation, -filesLimit, 2000, /opt/grobid/grobid-home/tmp/origin3229937128031954158.pdf, /opt/grobid/grobid-home/tmp/4wDQxkvfeZ.lxml]
ERROR [2022-04-06 14:07:25,987] org.grobid.core.process.ProcessPdfToXml: pdfalto return message: 

ERROR [2022-04-06 14:07:25,988] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs. 
```
You mention [here](https://github.com/kermitt2/grobid-example/issues/13) that this error can be a bit of anything. So let me know if you need more data for replicating the error. 
The server config is set on 10 threads and a timeout of 120 seconds, though I get this "timeout error" after 20 sec.

**Comment by kermitt2** [comment]
Hi @mazzespazze !

Thanks for using Grobid and reporting the issue.

The issue https://github.com/kermitt2/grobid-example/issues/13 was for Windows. I guess you are not using Windows since other papers were working. Which Grobid version are you using? Are you using the docker image? 

I try on my local machine and it works with current master. It works also with the online demo (a bit older master version). Both are with default settings for the timeout. 

For processing only the header, it is actually very fast for me:

```
time curl --form input=@./antioxidants-11-00251-v2.pdf localhost:8070/api/processHeaderDocument
real	0m0.166s
user	0m0.006s
sys	0m0.006s
```
For the complete document it's a slow, I guess because it is a large PDF with 50 pages with 347 bibliographical references:

```
 time curl --form input=@./antioxidants-11-00251-v2.pdf localhost:8070/api/processFulltextDocument
real	0m7.127s
user	0m0.014s
sys	0m0.017s
```
However there is no visible issue with the pdf parsing step. 

[antioxidants-11-00251-v2.pdf.tei.xml.gz](https://github.com/kermitt2/grobid/files/8458768/antioxidants-11-00251-v2.pdf.tei.xml.gz)

**Comment by mazzespazze** [comment]
I am using grobid 0.7.0 and I am on Ubuntu 20 as a client, and the server runs on a Linux machine in the cloud. 
As you say, the header only is fast and works for me as well, the fulltext processing instead gives me the bad xml. 

Perhaps is related with the grobid version? I'll try to upgrade the server to 0.7.1 and see if I get again the same issue.

**Comment by kermitt2** [comment]
Thanks for the clarification! Yes perhaps the new 0.7.1 version will solve the problem - it's the same one as I tested.

**Comment by mazzespazze** [comment]
@kermitt2 I can confirm that upgrading to version `0.7.1` solved the issue. In a parallel universe, it would be really nice to know what was it and how it was fixed. But, I am more than content with this being solved!

Thanks for the tip and sorry for the delay, a lot of stuff happened during Easter holidays that had priority.

**Comment by kermitt2** [comment]
@mazzespazze thanks for the feedback and good that this PDF is working now too !
To be honest I cannot immediately point to one of the fixes we made in the last months that has solved this problem, this is actually quite time consuming to track the problems back to the PDF parsing - which is likely where the trouble was taking place - so relatd to [pdfalto](https://github.com/kermitt2/pdfalto) or the interface with pdfalto.
