### ISSUE TITLE
Adding new tags 

### ISSUE THREAD

**Issue by Tanmay98** [kermitt2/grobid#938]
I am grateful for your help till now @kermitt2. Thankyou for always replying very fast.
So, I tried adding new tags in the fulltext model according to the way you explained in the issue #344. As you mentioned, I made the necessary changes in :

- TEIFulltextSaxParser.java
- TaggingLabels.java
- TEIFormatter.java

After training I was able to get some score for the new tag `<rs>` like below:
<img src=https://user-images.githubusercontent.com/31308303/182582795-c26ac928-bfb8-4065-b421-c5581f506ba0.png width="400" height="200" />

But when I try running create training method or processFulltext method, I am unable to get the <rs> tag as output. This is after making changes in the TEIFormatter.java file.

It will be a big help to me if you could tell me what I missed here. Thanks in advance !

**Comment by Tanmay98** [comment]
Hi @kermitt2 ! 
It will be a big help for me if you could tell me how to fix the above issue. 
Thanks in advance!

**Comment by Tanmay98** [comment]
Sorry for the inconvenience! It seemed to be an issue from my side. It is now working!

**Comment by kermitt2** [comment]
Hi @Tanmay98 ! Good to know and sorry I was off the last days.

**Comment by Tanmay98** [comment]
Hey @kermitt2 ! No problem. 
Also, I was able to add new tags in the fulltext as well as the header model.

**Comment by LakshmiNarayanan2003** [comment]
Hi @Tanmay98  & @kermitt2 ,
I'm trying to do the same with the header model.
I'm working with scientific articles that might include 'conflict of interest', 'running title', 'classification', and many more tags.
Tried the same using the <rs> tag and edited those 3 java files (instead of TEIFulltextSaxParser.java, edited TEIHeaderSaxParser.java)

Could you please help me by providing me the sample of the 
- Training data (header xml or in this case, fulltext, that'll do)
- TEIFulltextSaxParser.java
- TaggingLabels.java
- TEIFormatter.java

so I could cross verify what I did wrong and rectify it?

**Comment by LakshmiNarayanan2003** [comment]
> Sorry for the inconvenience! It seemed to be an issue from my side. It is now working!

Hey.
Facing the same issue.
What change did you make?
