### ISSUE TITLE
PDF to XML conversion time out for some files in server mode but run the pdfalto_server cmd in shell is fast and returns ok.

### ISSUE THREAD

**Issue by elonzh** [kermitt2/grobid#941]
### test file: 
[0cd4f6ed-0006-4b1a-a71d-0db0670050e0.pdf](https://github.com/kermitt2/pdfalto/files/9371810/0cd4f6ed-0006-4b1a-a71d-0db0670050e0.pdf)

### Service output

```text
org.grobid.core.process.ProcessPdfToXml: pdfalto process finished with error code: 143. 
[
  \\wsl$\Ubuntu\home\elonzh\workspace\grobid\grobid-home\pdfalto\lin-64\pdfalto_server, 
  -fullFontName, 
  -noLineNumbers, 
  -noImage, 
  -annotation, 
  -filesLimit, 2000, 
  /home/elonzh/workspace/grobid/grobid-home/tmp/origin11089783328378169294.pdf, 
  /home/elonzh/workspace/grobid/grobid-home/tmp/QCdS7b3245.lxml
]

Syntax Error (308820): Unknown operator 'd<1d><bd><fc><b2><13><0b><8c>'
Syntax Error (308880): Unknown operator 'D<05><9b>n#<ab><a9><bc><ec><97><af><18><e5><f6><f9>|<b8><bd><df><a5><eb><9a>r@<d7><c7><e7>'
Syntax Error (308881): Illegal character '>'
Syntax Error (308888): Illegal character '>'
Syntax Error (308896): Illegal character <dd> in hex string
...
Syntax Error (319522): Illegal character <fe> in hex string
```

### Shell output
```shell
$./grobid-home/pdfalto/lin-64/pdfalto_server 
-fullFontName 
-noLineNumbers 
-noImage 
-annotation 
-filesLimit 2000 
0cd4f6ed-0006-4b1a-a71d-0db0670050e0.pdf

Syntax Error (308820): Unknown operator 'd<1d><bd><fc><b2><13><0b><8c>'
Syntax Error (308880): Unknown operator 'D<05><9b>n#<ab><a9><bc><ec><97><af><18><e5><f6><f9>|<b8><bd><df><a5><eb><9a>r@<d7><c7><e7>'
Syntax Error (308881): Illegal character '>'
Syntax Error (308888): Illegal character '>'
Syntax Error (308896): Illegal character <dd> in hex string
...
Syntax Error (319522): Illegal character <fe> in hex string
...
Syntax Error (320317): Illegal character <9a> in hex string
Syntax Error: Unterminated string
Syntax Error: End of file inside array
Syntax Error: Leftover args in content stream
```

### Solution

I disabled the `pdfalto_server` output then everything works fine.

Changing `pdfalto_server` from

```shell
...
exec $command $@
```

to 

```shell
...
exec $command $@ 2> /dev/null
```

**Comment by elonzh** [comment]
Why do we need to wait for the process to finish via the shell?  From Java 8, `java.lang.Process#waitFor()` supports setting a timeout to wait subprocess complete, and we can call `destroyForcibly` to clean up the subprocess

**Comment by kermitt2** [comment]
Hi @elonzh 

This is normally fixed since a few week, see https://github.com/kermitt2/grobid/issues/923#issuecomment-1161971179
The stderr from pdfalto_server was blocking the java subprocess and your example PDF works with current master for me. 

> Why do we need to wait for the process to finish via the shell? From Java 8, java.lang.Process#waitFor() supports setting a timeout to wait subprocess complete, and we can call destroyForcibly to clean up the subprocess

I think the external timeout in the process script was written to forcibly kill the subprocess for JVM versions prior to Java 8 (this is very old part of Grobid, like 10 years old - at the time it was the best way to actually kill an external process). I suppose we could use indeed `destroyForcibly` now, but at the same time it is working very well as it is, so we focused on other aspects and didn't look at it again :)

But maybe there is another reason that I have forgotten.
