### ISSUE TITLE
Build failed with exception

### ISSUE THREAD

**Issue by sarique2003** [kermitt2/grobid#976]
I am using ubutntu 22.04 my java version is 8
The error that i have been getting is
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-service:run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 18s
9 actionable tasks: 3 executed, 3 from cache, 3 up-to-date

### **Stacktrace  command**
[https://drive.google.com/drive/u/0/search?q=sta](url)

### **WIth  info command**
[https://drive.google.com/drive/u/0/search?q=info](url)

**Comment by kermitt2** [comment]
Hi @sarique2003 !

I can't access the traces on google drive. 

Could you also indicate the version of grobid you are using?

**Comment by sarique2003** [comment]
Stacktrace = [https://drive.google.com/drive/u/0/search?q=sta]
info = [https://drive.google.com/drive/u/0/search?q=info]

Sorry for the mishap providing working links

**Comment by kermitt2** [comment]
@sarique2003 I am sorry, still can't access - these are search requests on google drives, not artifacts. 
If the stack traces are not too long, you could just cut and paste here, with the command line you used. 
Maybe you'd want to try more recent versions like 0.7.2 too ? (all should work fine on your environment)

**Comment by sarique2003** [comment]
Will try with newer version

**Comment by sarique2003** [comment]
https://drive.google.com/file/d/1wqtVpKBgVe4JXo9ILDJWI1szZWmZJmP5/view?usp=share_link =Stacktrace
https://drive.google.com/file/d/1zoXHHWteyOyziGRbMVShG9Hyuv7WGglt/view?usp=share_link= info

**Comment by kermitt2** [comment]
Thank you @sarique2003  ! 

Looking at the traces, the build is fine, the problem is running the service. It is due to a linking issue from the native Wapiti libraries which are included in Grobid. 

```
Caused by: java.lang.UnsatisfiedLinkError: /home/ravenclaw/Desktop/grobid/grobid-home/lib/lin-64/libwapiti.so: /home/ravenclaw/Desktop/grobid/grobid-home/lib/lin-64/libpthread.so.0: undefined symbol: __vdso_clock_gettime, version GLIBC_PRIVATE
```

It means that the native libraries shipped with Grobid try to link with your system libraries (which are incompatible, but it's normal) instead of the local libraries in the same directory (the other .so under grobid/grobid-home/lib/lin-64, in your case the local libc.so.6 normally).

1) Be sure to use a stable version and not the master. I've updated recently the native binaries and you are maybe using some unstable versions of the master native libraries, which could be a problem. You can download the releases [here](https://github.com/kermitt2/grobid/releases) and build/run from a release, not from the git repo to be sure to work with the stable versions. 

2) If you type:

> ldd grobid/grobid-home/lib/lin-64/libwapiti.so

The listed dependent libraries should have a local path (to grobid/grobid-home/lib/lin-64/ or just a local address), it should not reference your system libraries.

3) If you build/run from the current master only, it should normally work since 579939bb857badded0995d4ff74fe3bad5f9f485 (a `git pull` might be necessary).

**Comment by sarique2003** [comment]
Thank you @kermitt2 , the server is running now guess the version i was using was unstable, thanks again
