### ISSUE TITLE
Create a Hugging Face Spaces demo for Grobid

### ISSUE THREAD

**Issue by davanstrien** [kermitt2/grobid#987]
https://huggingface.co/spaces allows you to host machine learning demos for free. Hugging FaceSpaces has Docker support, so creating a hosted demo version of Grobid is possible. I think this would be a nice way for people to try out Grobid quickly with no local setup required. 

I've quickly created a POC for this here: https://huggingface.co/spaces/davanstrien/grobid. You can also see the non-embded version here: https://davanstrien-grobid.hf.space/  

Happy to help with creating this if it's of interest. 
cc @libcce

**Comment by davanstrien** [comment]
At the moment you can't configure the run command, but it should be possible to do this by updating the Dockerfile. The one I created (https://huggingface.co/spaces/davanstrien/grobid/blob/main/Dockerfile) basically just uses the existing Grobid image and sets some permissions. 

You could update the Dockerfile I created and include the config files in the Spaces repo i.e. in https://huggingface.co/spaces/davanstrien/grobid/tree/main and copy it in the image with `COPY --chown=user <some-file-in-repo> <dest-in-image>.`

It's also possible to get a community grant for GPU spaces see: https://huggingface.co/docs/hub/spaces-gpus#using-gpu-spaces which might be helpful for making the demo a bit more performant.

**Comment by kermitt2** [comment]
Thank you very much @davanstrien for the issue and the POC !

It can be a really great to solution to host a demo with the Deep Learning models and GPU, because the current [public demo](https://grobid.science-miner.com) and the [play-with-docker](https://github.com/kermitt2/grobid#try-in-play-with-docker) solution only use CRF models, which are clearly not as good as the DL models. The public demo hosted on a Linode CPU server cost me a $1000 per year from my pocket actually (don't tell my wife).

In the POC, there are currently 2 issues: 
- the embedded web demo/console is not working (it will return error 405), because the web console is a bit too dumb to work with this modified url, but it is easy to fix (the non-embedded version works)
- the selected docker image normally uses Deep Learning models for bibliographical reference parsing and affiliation parsing, however both are not working, I suppose because the POC is running on CPU only and likely without enough memory to load the DL models in CPU RAM. So without GPU I suppose it's not a solution when using DL models. 
 
I will explore the GPU community grant possibility, which should solve the second problem. As an alternative, the first GPU space cost is anyway 2 times cheaper than my current Linode CPU-only solution. 

So in any cases, even with CPU, it can be a nice replacement for the current demo.

**Comment by lfoppiano** [comment]
I've managed to deploy [grobid-quantities](https://lfoppiano-grobid-quantities.hf.space) and [grobid-superconductors](https://lfoppiano-grobid-superconductors.hf.space). 
The embedded version suffers the same issue but the normal URL works very well! :-)

**Comment by kermitt2** [comment]
@lfoppiano did you manage to get DL models working with the CPU-only environment ?

**Comment by davanstrien** [comment]
>     * the embedded web demo/console is not working (it will return error 405), because the web console is a bit too dumb to work with this modified url, but it is easy to fix (the non-embedded version works)
This is an issue people have run into, good to hear the non-embedded version works :) 

>     * the selected docker image normally uses Deep Learning models for bibliographical reference parsing and affiliation parsing, however both are not working, I suppose because the POC is running on CPU only and likely without enough memory to load the DL models in CPU RAM. So without GPU I suppose it's not a solution when using DL models.
> 
You could also try with an upgrade CPU (this also comes with more memory 32GB rather than 16) full breakdown of spaces hardware here: https://huggingface.co/docs/hub/spaces-overview#hardware-resources. The container logs may also give you an idea if it's a memory issue. IIRC I also ran into some memory issues with the POC for some of the tasks. 

> I will explore the GPU community grant possibility, which should solve the second problem. As an alternative, the first GPU space cost is anyway 2 times cheaper than my current Linode CPU-only solution.
> 
> So in any cases, even with CPU, it can be a nice replacement for the current demo.
🤗

**Comment by kermitt2** [comment]
I set up a demo CRF-only with a fix for the embedded web demo/console and it works really well :)

https://huggingface.co/spaces/kermitt2/grobid-crf

Thank you again @davanstrien for the super suggestion and the POC, it is really easy. 

I was too fast about cost, the cost of a GPU for a space at huggingFace is five times more than what I spend currently for the Grobid demo CPU server. So I'll try the community grant for GPU spaces.  

@lfoppiano The fix for the web client is very simple, line 27-30:
https://github.com/kermitt2/grobid/blob/master/grobid-service/src/main/resources/web/grobid/grobid.js#L27
It removes the url parameters after the `?`, which was causing the problem to get the correct end point for the service.

**Comment by kermitt2** [comment]
Regarding the second problem with the Deep Learning models not working, it was not related to the memory but to some access right paths to be added in the Dockerfile. This is now working well here: 

https://huggingface.co/spaces/kermitt2/grobid

This is based on a docker image using 3 deep learning models (for parsing article header, affiliation/address and bibliographical references - the rest is still CRF). The runtime with CPU only is actually not that bad at all. 5s server runtime for a pretty long articles instead of 3s with CRF only. 

@davanstrien really nice build container log console, really good work by HuggingFace I must say.

**Comment by lfoppiano** [comment]
> @lfoppiano did you manage to get DL models working with the CPU-only environment ?

I did not try. I deployed the CRF-only versions and applied for the GPU for grobid-superconductors. 

> @lfoppiano The fix for the web client is very simple, line 27-30:
> https://github.com/kermitt2/grobid/blob/master/grobid-service/src/main/resources/web/grobid/grobid.js#L27
> It removes the url parameters after the `?`, which was causing the problem to get the correct end point for the service.

thanks! :-) I will gladly cherry-pick it :-)

**Comment by davanstrien** [comment]
> Regarding the second problem with the Deep Learning models not working, it was not related to the memory but to some access right paths to be added in the Dockerfile. This is now working well here:
> 
> [huggingface.co/spaces/kermitt2/grobid](https://huggingface.co/spaces/kermitt2/grobid)
> 
> This is based on a docker image using 3 deep learning models (for parsing article header, affiliation/address and bibliographical references - the rest is still CRF). The runtime with CPU only is actually not that bad at all. 5s server runtime for a pretty long articles instead of 3s with CRF only.
> 
> @davanstrien very nice build container log console, really good work by HuggingFace I must say.

That's great to hear! Very happy that this is working well :) Do feel free to request a community grant for the GPUs if that becomes useful at some point.

**Comment by lfoppiano** [comment]
> That's great to hear! Very happy that this is working well :) Do feel free to request a community grant for the GPUs if that becomes useful at some point.

I've tried like one month ago but I got no answers. I did it here: https://huggingface.co/spaces/lfoppiano/grobid-superconductors/discussions/1#63eec0fabe5d5900b851c513 is it correct?

**Comment by gjreda** [comment]
Hi - I came across this issue while trying to debug why I wasn't seeing any results in the HF space. I dropped a [comment on the HF space](https://huggingface.co/spaces/kermitt2/grobid/discussions/2), but I was wondering if that is still working as expected.

Thanks for your help!

**Comment by lfoppiano** [comment]
@gjreda how many pages was the PDF?

**Comment by gjreda** [comment]
@lfoppiano followed up with me on the HF space and I think that clarifies my issue

**Comment by lfoppiano** [comment]
😄  👍

**Comment by davanstrien** [comment]
> > That's great to hear! Very happy that this is working well :) Do feel free to request a community grant for the GPUs if that becomes useful at some point.
> 
> I've tried like one month ago but I got no answers. I did it here: [huggingface.co/spaces/lfoppiano/grobid-superconductors/discussions/1#63eec0fabe5d5900b851c513](https://huggingface.co/spaces/lfoppiano/grobid-superconductors/discussions/1#63eec0fabe5d5900b851c513) is it correct?

Sorry, I somehow missed this. Let me see if it's possible to get a grant for a period of time.
