### ISSUE TITLE
Missing 'T' letter in the output xml file

### ISSUE THREAD

**Issue by nimsala1234** [kermitt2/grobid#988]
I used fulltext model and in the output xml file, the "T" is missing. Just the capital 'T' , not other superscripts. Is there any way of fixing this and I would like to know the reason for this too?

**Comment by kermitt2** [comment]
Hi @nimsala1234 !

Thanks for the issue. Could you share the PDF so that we can reproduce the problem and see how to fix it?

**Comment by nimsala1234** [comment]
It is 60mb large.

**Comment by nimsala1234** [comment]
Sorry for the delay. Here's the pdf. https://enarm.com.mx/catalogo/31.pdf

**Comment by kermitt2** [comment]
Hi @nimsala1234 the link is not working for me ("can’t connect to the server at enarm.com.mx"). Maybe could you create a PDF with just one page containing the problem for this letter and share it here?

**Comment by nimsala1234** [comment]
Let me put the pdf into the drive and share with you

**Comment by kermitt2** [comment]
Yes I could access it, you can remove it from public access. 
I'll look at the issue later tonight.

**Comment by kermitt2** [comment]
I check the PDF for the "missing T" and it is due to the font that uses a ligature for "Th". This is a rare ligature, I know it exists for handwriting-style typeface, but it's the first time I see it in a formal publication. It's called a "decorative ligature".

The main problem is that there is no unicode codepoint for this ligature "Th" apparently: https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)

So I don't know how to detect this ligature and map it to the right 2 character sequence when parsing a PDF. This is basically a font with a custom glyph that cannot be resolved to a unicode unfortunately.

**Comment by nimsala1234** [comment]
> Yes I could access it, you can remove it from public access. I'll look at the issue later tonight.

Thank you so much Patrice!

**Comment by nimsala1234** [comment]
> I check the PDF for the "missing T" and it is due to the font that uses a ligature for "Th". This is a rare ligature, I know it exists for handwriting-style typeface, but it's the first time I see it in a formal publication. It's called a "decorative ligature".
> 
> The main problem is that there is no unicode codepoint for this ligature "Th" apparently: https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)
> 
> So I don't know how to detect this ligature and map it to the right 2 character sequence when parsing a PDF. This is basically a font with a custom glyph that cannot be resolved to a unicode unfortunately.

Hmm Is that so.. Anyways Thank you so much Patrice for looking into that and also explaining all of this! Really appreciate that!
