### ISSUE TITLE
single file conversion

### ISSUE THREAD

**Issue by kaschioudi** [kermitt2/grobid#99]
Hello,

The documentation provides examples of how to convert an entire directory (batch mode). Is there a way to convert a single file? I would like to specify the path to a pdf document and the directory into which tei xml file should be created. I have looked around and was unable to find how to do so.

**Comment by lfoppiano** [comment]
Dear @kaschioudi, 
    the idea behind the 'batch mode' is to convert big quantity of data. If you want to convert only one file, I would recommend you to use GROBID as a service and write your own script that post it through the web interface (see [here](http://grobid.readthedocs.io/en/latest/Grobid-service/))

Regards
Luca

**Comment by kaschioudi** [comment]
Okay. thank you for your reply

**Comment by jalperin** [comment]
Is this something that you might consider adding? We certainly have a use case for it, and it'd be easier than running it as a service. Would appreciate it, if it's trivial on your end.

**Comment by lfoppiano** [comment]
@jalperin, I'd be happy to consider the idea. Could you please clarify your use case end 2 end?

**Comment by kermitt2** [comment]
Hi! 

It is of course straightforward to add a single file command line process. The reason why it is not present currently is that, in such case, most of the processing time is spent for loading the models and lexicon, not processing the file. I think loading all the resources just for processing one file is not a usage to promote.

Since it is possible to use very easily the service (just on command line to start it) for processing files one by one (with both the advantage of the web console and the curl command line), keeping the benefit of having all the models and resources "warm" and multithreading, I think it is better not to add a usage that would lead to an inefficient/degraded usage of the tool. 

But if you are not convinced by my arguments, let's add it :)
